### ISSUE TITLE
[Feature]: Add a `post_init` method to `get_class` 

### ISSUE THREAD

**Issue by h-mayorquin** [hdmf-dev/hdmf#1072]
### What would you like to see added to HDMF?

Extensions creates can build an API for their work using the following:

```python
AClass = get_class("ObjectOnTheSpec", "ndx-extension")
```

It would be nice to have a mechanism to do checks with their arugments when using the `get_class` convenience method. 

### What solution would you like?

Something that looks like this:

```python
def post_init(**init_kwargs):
    
    # Do the check here

ACheckedClass = get_class("ObjectOnTheSpec", "ndx-extension", post_init=post_init)
```

### Do you have any interest in helping implement the feature?

No.

**Comment by bendichter** [comment]
Following the syntax for [post_init in Python dataclasses](https://docs.python.org/3/library/dataclasses.html#dataclasses.__post_init__), let's use this call signature `def post_init(self)`
