### ISSUE TITLE
Cannot write multi-dimensional string arrays

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#1137]
This only works for 1-D string arrays. I think the if statement in this code is intended to check for structured arrays / compound dtypes. Else, execution should go to `get_data_shape` which gets the shape correctly. 

https://github.com/hdmf-dev/hdmf/blob/7426275cacc769a10ffca89836765df1355ba9db/src/hdmf/backends/hdf5/h5tools.py#L1472-L1473

**Comment by stephprince** [comment]
See related issue here with tests: https://github.com/hdmf-dev/hdmf/issues/1096
