### ISSUE TITLE
[Feature]: Update tests to use numpy 2.0

### ISSUE THREAD

**Issue by mavaylon1** [hdmf-dev/hdmf#1177]
### What would you like to see added to HDMF?

Pandas and scipy support numpy 2.0. Update the tests to use most up to date packages, and update the pyproject.toml with new minimums.

### What solution would you like?

Above

### Do you have any interest in helping implement the feature?

Yes.

**Comment by rly** [comment]
I don't think we need to bump up the minimums unless there are features in numpy 2 that we really want to use. HDMF supports numpy 2 as of 3.14.2.
