### ISSUE TITLE
Bonsai GUI export to NWB

### ISSUE THREAD

**Issue by justidy1** [hdmf-dev/hdmf#1196]
### What would you like to see added to HDMF?

Support for NWB export in Bonsai 

### What solution would you like?

A bonsai interface for NWB

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance.

**Comment by oruebel** [comment]
@justidy1 do you know what languages Bonsai supports to create plugins? As far as I can tell it uses C#, but I was wondering whether it may also support Python? I am not too familiar with C#, but if Bonsai requires C# for plugins then some options may be to either: 1) use Python.NET to call functions in PyNWB, 2) use SWIG to wrap the AqNWB C++ API for C#, or 3) use HDF5 directly.

**Comment by justidy1** [comment]
In talking with the Bonsai team at SfN, they mentioned a newer node that users can put in custom python scripts (instead of Python.NET) which I understand could call PyNWB. As far as Python support for proper plugins, I do not know.

**Comment by rly** [comment]
Closing this issue in favor of an open ticket in the Bonsai github: https://github.com/bonsai-rx/bonsai/issues/2041
