### ISSUE TITLE
Default mapping of child attributes depends on order the attrs are read

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#129]
If a Container, e.g. `VoltageClampSeries`, has multiple datasets, e.g. `data`, `capacitance_fast`, with the same named attribute, e.g. `unit`, then the first spec named `unit` that gets encountered by the ObjectMapper gets mapped to the `unit` attribute on the `VoltageClampSeries` class. Specs with the name `unit` encountered later get mapped to the attribute name `{dataset_name}_unit`, e.g. `data_unit`. 

Normally, this is fine: e.g. for `TimeSeries`, there is only one dataset/group with a `unit` attribute -- the `data` dataset, so the `unit` attribute spec of `TimeSeries.data` will be mapped to the `unit` attribute on TimeSeries. But when there are multiple datasets, which `unit` spec gets encountered first and is used to set the root level attribute on the class is arbitrary. On Python 3.5, this happens non-deterministically...

Proposed change: 

In `map.py`, in `ObjectMapper.__get_fields`, change:
```python
if name in all_names:
  name = '_'.join(name_stack)
```
to:
```python
name = '__'.join(name_stack)
```

This means all attribute specs of children will be mapped to a class attribute like 'parent1__parent2__parent3__attrname'. These usable, these specs need to be remapped explicitly to a more convenient name. There are a few classes in PyNWB that are affected by this: VoltageClampSeries, ImageSeriesMap, ImagingPlaneMap

And rather than use '\_' for the delimited between a spec's parents in the default class attribute name, use '\_\_' (two underscores), to make it less confusing with attribute names that use '_' as a word delimiter. We _could_ completely remove this functionality of mapping child attributes to e.g. 'parent1__parent2__parent3__attrname' and make it so this mapping must be done explicitly in the class' ObjectMapper, but this approach would be cumbersome for dynamically generated classes.

**Comment by bendichter** [comment]
I think this is better for dynamically created classes too as this makes it clear what the name would be
