### ISSUE TITLE
Support HDF5 Virtual Datasets on Write

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf#135]
For very-large data arrays it can be useful to split the data across files to avoid creation of overly large single files. 

HDF5 supports the concept of VirtualDatasets, which allows a dataset in a file to be composed of subblocks from Datasets stored in external HDF5 files. Using this approach allows single large arrays to be broken up in to sub-files while exposing to the user the same interface as if the data where stored in a single array. As such, HDMF already supports read of VirtualDatasets, however, it currently does not support creation of VirtualDatasets on write. To support creation of VirtualDatasets we'd need to:

* Update H5DataIO to allow specification of the layout of the sub-files, i.e., define how the virtual dataset should be broken up into sub-blocks
* Define a naming-convention for creating sub-files (e.g., we could store all sub-files in a subfolder along with the HDF5 file and name them according to their location in the main file plus a running index for the block)
* In HDF5IO we would need to add a method to create virtual datasets. The main write functions should be able to remain as is (since we can write into a VirtualDataset) but how we create the dataset would need to change when a VirtualDataset is required 

See http://docs.h5py.org/en/stable/vds.html for a short intro to VDS in h5py

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by jisonZ** [comment]
Do they support write on VDS now? I'm also encountering this issue

**Comment by oruebel** [comment]
@jisonZ Unfortunately we have not gotten around to implementing this feature yet. So far we didn't really have any requests yet from users that need this feature, i.e., this has been more in the category of nice-to-have. It would be great if you could describe your use-case for this feature a bit more to help us better understand your needs.

**Comment by jisonZ** [comment]
Our current project involve tracing neurons over an brainbow image and basically the tracing result is stored in a hdf5 file (image as a 2d matrix). We split one brainbow image into several hdf5 files ( its size too big alone for loading into applications) and when the user is tracing over a specific area, we retrieve the hdf5 files that include this area and construct a VDS of this area as an input to the app. Therefore, It's also important to store the user's modification back to the VDS and thus the individual files that are involved constructing the VDS. I believe that's where the VDS write comes in

**Comment by jisonZ** [comment]
I'm very confused while reading the hdf5 official documentation about the read/write over VDS. it seems like they kinda provide this feature??? but I'm using the h5py and I could not find how to do this whatsoever. I noticed this issue while searching for answers, looks like y'all working on extra features for HDF5?

**Comment by oruebel** [comment]
@jisonZ since your data is already in HDF5, you may not actually need this feature. I think instead what you can do is simply create an external link to your existing VDS dataset. I believe h5py deals with VDS datasets transparently on read, i.e., I think reading the data should already work. 

> ... but I'm using the h5py and I could not find how to do this whatsoever.

The documentation for how to use VDS from h5py is at https://docs.h5py.org/en/stable/vds.html The page also includes links to a few simple example python scripts for how to assemble a collection of existing datasets to a VDS, e.g., https://github.com/h5py/h5py/blob/master/examples/vds_simple.py I hope this helps. 

>  I noticed this issue while searching for answers, looks like y'all working on extra features for HDF5?

This issue is to support creating new VDS datasets via HDMF not to change h5py/HDF5. HDMF defines its own abstract I/O layer to transparently deal with the translation of data standards to disk and to allow for the integration of other storage solutions (e.g., Zarr) and to make the use of different storage solutions largely transparent for users. HMDFs I/O backend for HDF5 uses h5py but does not yet expose all the features of h5py through HDMF. Support for storing data in VDS via HDMF is one of the features that is missing.

**Comment by jisonZ** [comment]
@oruebel Thanks a lot for the response! I understand that h5py VDS reading is possible and we are actually using this feature such that the application could present the image stored in the VDS. In our case, suppose we have an original rainbow image called bb.tiff that is segmented into img_1.h5, img_2.h5, img_3.h5, img_4.h5 and we would construct a VDS (which represent a segment of the bb.tiff image that is, unfortunately, included in both 4 files above) as an input to the application, yet what we want is for the user to make a modification to the presented image and write is back to the 4 files. It would be a bit of hustle to refer each section back to each individual file that constructs the VDS without directly write on the VDS. Sorry for not being really clear in the previous responses, or I'm missing what you said by "create an external link to your existing VDS dataset", I'm a bit confused by what an external link means.

**Comment by jisonZ** [comment]
@oruebel Also another thing that I really would like to confirm with you is that HDF5 currently does not support write on VDS, at least the h5py does not support an API that does this. I just got my hands on HDF5 so would need some help from someone who's more experienced :)

**Comment by oruebel** [comment]
> I'm a bit confused by what an external link means.

In HDF5 you can include datasets and groups from other HDF5 files via links. HDF5 here distinguishes between three main types of links: 1) Hard Links point to an object in the same file and just store the Id of the object, 2) Soft Links also point to an object in the same file but the link is distinct from the original object so you can tell which is original and which is the link, and 3) External Links are like softlinks but they point to Datasets or Groups that are in another file. In your case, if you already have and HDF5 file with the VDS and you want to include it in a file that you write with HDMF you could just link to your existing VDS. 

> confirm with you is that HDF5 currently does not support write on VDS

I am not an expert on VDS. That is a question that you should pose to the HDF5 or h5py team. Maybe create an issue on the h5py repo. I believe HDF5 itself does support write to VDS but I am not sure. Let me know if you find the answer.

**Comment by jisonZ** [comment]
@oruebel https://github.com/h5py/h5py/issues/1798

**Comment by oruebel** [comment]
h5py 3.3 now has a context manager for creating VDS: https://docs.h5py.org/en/stable/high/group.html#h5py.Group.build_virtual_dataset

**Comment by mavaylon1** [comment]
Closed due to comment: https://github.com/hdmf-dev/hdmf/issues/644
