### ISSUE TITLE
DataChunkIterator converting data to float

### ISSUE THREAD

**Issue by luiztauffer** [hdmf-dev/hdmf#140]
## Description

`pynwb==1.1.0.post0.dev1` and `hdmf==1.2.0.post0.dev1`
I’m trying to store `int16` data using DataChunkIterator but it seems to be converting dtype to `float`. Here’s an example:

```python
from datetime import datetime
from dateutil.tz import tzlocal
from pynwb import NWBFile
from pynwb import NWBHDF5IO
from pynwb.ecephys import ElectricalSeries
from hdmf.data_utils import DataChunkIterator
import numpy as np
import os

nwb = NWBFile(session_description='session', identifier='1', session_start_time=datetime.now(tzlocal()))

# Add electrode groups and channels
nChannels = 10
dev0 = nwb.create_device(name='dev0')
elecs_group = nwb.create_electrode_group(name='electrodes', description='', location='ctx', device=dev0)
for i in np.arange(nChannels):
    ii = float(i)
    nwb.add_electrode(x=ii, y=ii, z=ii, imp=ii, location='', filtering='', group=elecs_group)

#Add signal
elecs_region = nwb.electrodes.create_region(name='electrodes',
                                            region=np.arange(nChannels).tolist(),
                                            description='')

def data_generator(nChannels):
    X_data = np.zeros((nChannels,1000)).astype('int16')
    for id in range(0, nChannels):
        data = X_data[id,:]
        print(data.dtype)
        yield data
data = data_generator(nChannels=10)
iter_data = DataChunkIterator(data=data, iter_axis=1)

signal = ElectricalSeries(name='ElectricalSeries', 
                          data=iter_data, 
                          electrodes=elecs_region,
                          starting_time=0.,
                          rate=1.)
nwb.add_acquisition(signal)

#Write file
with NWBHDF5IO('file_1.nwb', mode='w') as io:
    io.write(nwb)
    
# Read file
io = NWBHDF5IO('file_1.nwb', 'r+')
nwbfile = io.read()
print(nwbfile.acquisition['ElectricalSeries'].data[:,0].dtype)
io.close()
```

If I pass the data directly, it works fine:
```python
# iter_data = DataChunkIterator(data=data, iter_axis=1)
iter_data = np.zeros((nChannels,1000)).astype('int16')
```
## Checklist

- [ x] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [ x] Have you included a brief and descriptive title?
- [ x] Have you included a clear description of the problem you are trying to solve?
- [ x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [ x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment]
reproduced, and is still an issue if `iter_axes=1` is omitted

**Comment by oruebel** [comment]
Have you tried setting the dtype explicitly in the constructor of DataChunkIterator via

```iter_data = DataChunkIterator(data=data, iter_axis=1, dtype=np.dtype('int16'))```

If that fixes the issue then this should be an issue either  in the generator function or the constructor of DataChunkIterator.

**Comment by luiztauffer** [comment]
thanks for the suggestion, but it did not solve the issue
