### ISSUE TITLE
'numeric' dtype in spec acts as None dtype

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#142]
Related to #140 

For most subtypes of TimeSeries, the "data" dataset has the spec 'dtype: numeric'. In fact, that is the only place in the NWB schema where 'numeric' is used. 

As far as I can see, the only times that 'numeric' is actually used in HDMF are in the validator and in the following code:
https://github.com/hdmf-dev/hdmf/blob/5a9a9cb5f371dcb66c1f08ab84cef4c8506f4e69/src/hdmf/build/map.py#L474-L477

where 'numeric' serves the same purpose as not specifying a dtype at all. 

When `value, None` is returned above, this None is used as the dtype for the DatasetBuilder, and this messes with code downstream where 'dtype=None' is used when writing an AbstractDataChunkIterator (#140).

The above code logic seems like it would also cause other problems that have not yet come up. For example, I can write a list of strings for 'data' of an ElectricalSeries:
```python
signal = ElectricalSeries(name='ElectricalSeries',
                          data=['hello'],
                          electrodes=elecs_region,
                          starting_time=0.,
                          rate=1.)
```
Writing and reading this works just fine, but this should not be allowed. I think the check for that should be somewhere in HDMF, though I have not yet found it. Help in tackling this would be appreciated.

**Comment by oruebel** [comment]
> this messes with code downstream where 'dtype=None' is used when writing an AbstractDataChunkIterator

When does this happen, i.e., when would  dtype for DataChunkIterator be allowed to be None? As far as I can tell the dtype for a DataChunkIterator should be either provided by the user, determined by __init__, or fail if the dtype can't be determined.

**Comment by rly** [comment]
The DataChunkIterator has the correct type. But in `__chunked_iter_fill__`:
https://github.com/hdmf-dev/hdmf/blob/5e6a2f6696d4a86def91c0bb5b124dee85985d1c/src/hdmf/backends/hdf5/h5tools.py#L843-L895

The passed `options` has a `dtype = None` specified from the DatasetBuilder. `io_settings['dtype'] is thus assigned from there instead of `data.dtype`.
