### ISSUE TITLE
H5DataIO.chunks arg ignored for strings

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#162]
For https://github.com/NeurodataWithoutBorders/pynwb/issues/1067 we need to have string vectors that are chunked. When I try to chunk string objects in pynwb (using hdmf), they result in a dataset that is not chunked. When I try chunking them in h5py there is no problem and they are chunked as expected.

```python
from datetime import datetime
from dateutil.tz import tzlocal
from pynwb import NWBFile, NWBHDF5IO, TimeSeries
from pynwb.misc import AnnotationSeries
from hdmf.backends.hdf5 import H5DataIO


tso = TimeSeries(name='test_ts', data=H5DataIO(data=[1, 2, 3], chunks=True), timestamps=[1, 2, 3])
aso = AnnotationSeries(name='test_AS', data=H5DataIO(data=('aa', 'bb'), chunks=True), timestamps=(1., 2.))
nwb = NWBFile(session_description='session', identifier='1', session_start_time=datetime.now(tzlocal()))
nwb.add_acquisition(aso)
nwb.add_acquisition(tso)

with NWBHDF5IO('test_file.nwb', 'w') as io:
    io.write(nwb)

with NWBHDF5IO('test_file.nwb', 'r') as io:
    nwb = io.read()
    print('TimeSeries:')
    print('{}, {}'.format(nwb.acquisition['test_ts'].data.dtype, nwb.acquisition['test_ts'].data.chunks))
    print('')
    print('AnnotationSeries:')
    print('{}, {}'.format(nwb.acquisition['test_AS'].data.dtype, nwb.acquisition['test_AS'].data.chunks))


from h5py import File, special_dtype
import numpy as np

file = File('test.h5', 'w')
aa = file.create_dataset(name='test_ds', data=np.string_((u'aa', u'bb')), dtype=special_dtype(vlen=str),
                         chunks=True)
print('')
print('vlen-str in h5py:')
print('{}, {}'.format(aa.dtype, aa.chunks))
```

```
TimeSeries:
int64, (3,)

AnnotationSeries:
object, None

vlen-str in h5py:
object, (2,)
```

**Comment by oruebel** [comment]
Can you try the following:

1) Change your data from a tuple to a list (i.e., use ``['aa', 'bb']`` to ``('aa', 'bb')``)
2) Specify the dtype in H5DataIO to str

**Comment by bendichter** [comment]
@oruebel `H5DataIO` doesn't take a `dtype` arg. Making the data a list made no difference.

**Comment by oruebel** [comment]
@bendichter thanks. I'll take a look in a bit to see what's going on.

**Comment by oruebel** [comment]
I have not found the solution yet, but I think the problem may be with ``AnnotationSeries`` rather than on the H5DataIO/HDF5IO side. When using a base TimeSeries with strings the chunking seems to work, i.e. write this

`` TimeSeries(unit='text', name='test_AS', data=H5DataIO(data=['a', 'aa', 'bbb' , 'ccsd' , 'fgd', 'asd'], chunks=True), timestamps=[1., 2., 3. ,4. ,5., 6.])``

instead of the AnnotationSeries.

**Comment by bendichter** [comment]
@oruebel you are right, that works! So I guess this is a problem with some particular neurodata types and not others. I originally ran into this issue with table columns. It would be great to have this working for `AnnotationSeries` though as I could see a user wanting to add data there as well.

**Comment by oruebel** [comment]
>  It would be great to have this working for `AnnotationSeries`

Agreed, this needs to work the same way across types. This is just one step in me trying to trace down the source of the problem ;-)
