### ISSUE TITLE
DynamicTableSpec convenience class

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf#169]
Since DynamicTable is part of the hdmf-core schema, would it make sense to have convience DynamicTableSpec class to facilitate specification of extensions of DynamicTable types? E.g., we could have a add_column and add_indexed_column convenience functions to make it easier to add columns to the table. I'm not sure if that will make things more complicated (e.g., we'd have to also detect this when reading schema) or easier. I just figured I propose the idea.

## Checklist

- [ ] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [ ] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [ ] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
I think this would make it more complicated. It would also be a lot to maintain, given the number of options available for configuring a DynamicTable.
