### ISSUE TITLE
Document AbstractContainer.__fields__ in HDMF and PyNWB

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf#181]
The ``Container`` class supports the specification of ``__fields__`` in PyNWB these are described as a list of strings https://pynwb.readthedocs.io/en/stable/building_api.html#nwbfields and they seem to be omitted in the HDMF docs https://hdmf-dev.github.io/hdmfdocs It will be useful to update/add documentation for __fields__. In particular __fields__ allows for lists for dicts with the keys ``{'name', 'child', 'required_name', 'doc', 'settable'}`` and it would be useful to document the specific function of those keys both in HDMF and PyNWB

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by mavaylon1** [comment]
#827
