### ISSUE TITLE
Validator should check for quantity

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#197]
Currently, the validator checks whether required fields are present, but does not validate that a dataset conforms to the `'quantity'` field. For example, in PyNWB, `NWBFile` has quantity `'+'` for `Device`, which means at least one is required. However, files without a Device pass the validator. Similarly for `Position` requiring at least one `SpatialSeries`, `LFP` requiring at least one `ElectricalSeries`, etc.

**Comment by dsleiter** [comment]
I am currently working on an implementation for this.
