### ISSUE TITLE
schema yaml validator

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#2]
We should have a tool that checks the yaml files to make sure that schema specification files are correct. In other words, a meta-schema validator that checks the core and any extension schema files. This will be particularly useful for extension sharing, so we could run submitted extensions through an automated validator to ensure that they are at least syntactically correct.

https://json-schema.org/ would be a good tool for this.

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment]
This tool would have prevented https://github.com/NeurodataWithoutBorders/nwb-schema/issues/344

**Comment by rly** [comment]
Already done in #332
