### ISSUE TITLE
On read, raise helpful error message if DynamicTableRegion index is out of bounds

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#209]
If a `DynamicTableRegion` index that is out of bounds, the reported error is "Could not construct DynamicTableRegion object". This message is vague and should say that the index is out of bounds and which `DynamicTableRegion` object is problematic.

**Comment by mavaylon1** [comment]
I believe this has been solved on line 1294 for DynamicTableRegion. @rly 
https://github.com/hdmf-dev/hdmf/blob/dev/src/hdmf/common/table.py
```
raise IndexError('index {} out of bounds for data of length {}'.format(arg, len(self.data)))
```
