### ISSUE TITLE
Make backend handle reserved attributes

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#222]
A request from @oruebel:

Currently, there are three reserved attributes on the backend for HDMF: 'namespace', 'data_type', and 'object_id'. These are stored as attributes on builders and then the HDF5 backend writes them out as HDF5 attributes. Instead, the builders should store these reserved attributes under specific fields and let the backend decide how the attributes should be written. This is relevant for the implementation of dimension scales where 'dimensions' and 'coordinates' would be added as new reserved attributes.

Practically speaking, this change _should_ just be a refactoring and addition of fields, getters, and setters on the builder. 

What do you think @ajtritt?

**Comment by t-b** [comment]
@rly Can we have a chat how this could be implemented? I would need access to the reserved attributes so that I can ignore these for https://github.com/NeurodataWithoutBorders/pynwb/issues/942?

**Comment by rly** [comment]
See PR #400 for resolution. This is put on hold until there is a clear need.
