### ISSUE TITLE
empty Containers not writing

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#224]
I am creating an extension that inherits from `DynamicTable`, and am having trouble with the write step. When I run this script:

```python
from datetime import datetime
from pynwb import NWBFile, NWBHDF5IO
from hdmf.common.table import DynamicTable

nwb = NWBFile('session_description', 'identifier', datetime.now().astimezone())

dyn_tab = DynamicTable(name='name', description='desc')

behavior_mod = nwb.create_processing_module('behavior', 'desc')
nwb.processing['behavior'].add(dyn_tab)

print('before write')
print(nwb.processing['behavior'].data_interfaces)

# Write nwb file
with NWBHDF5IO('test_table.nwb', 'w') as io:
    io.write(nwb)

# Read nwb file and check its content
with NWBHDF5IO('test_table.nwb', 'r', load_namespaces=True) as io:
    nwb2 = io.read()
    print('after read')
    print(nwb2.processing['behavior'].data_interfaces)
```

the DynamicTable is not there on read. Upon inspecting the HDF5 file, it was never written. Can pynwb write hdmf-common types? I thought DynamicTables were writable on their own at some point. Did that change? If I wanted to write an extension that extended hdmf.common.DynamicTable and is writable, how would I do that?

    Python Executable: Conda 
    Python Version: Python 3.7
    Operating System: macOS
    pynwb '1.1.2.post.dev13'

**Comment by oruebel** [comment]
I would guess this may have to do with the move of things to hdmf-common @ajtritt ?

**Comment by ajtritt** [comment]
This is intended behavior.

According to this line, no empty containers get written
https://github.com/hdmf-dev/hdmf/blob/55dc7dd2b51f4725bd818fb58eb8d811319279a2/src/hdmf/build/objectmapper.py#L818

That should probably be removed if we want to create a file from template for populating elsewhere.

**Comment by bendichter** [comment]
yes, that was it. Thanks @ajtritt. 

What was the reasoning behind not writing empty containers? Do they come up a lot? I would prefer having the ability to write them, in case, as you said, we want a place-holder for populating later.

**Comment by ajtritt** [comment]
I don't know the exact reasoning, it's probably really old. I'm fine with lifting the restriction.
