### ISSUE TITLE
shape of VectorIndex

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#228]
## Description

When `docval` checks the shape of `VectorIndex`, it returns the shape of the referenced table. It should instead check the shape of `VectorIndex.data`
## Steps to Reproduce

```python
from hdmf.common.table import VectorIndex, VectorData
from hdmf.utils import docval


data = [[1., 1., 1.], [2., 2., 2.], [1., 2., 1.]]
data_vect = VectorData(name='vec', description='desc', data=data)

indexes = [2, 3]
data_ind = VectorIndex(name='vec_index', data=indexes, target=data_vect)

@docval({'name': 'vec_index', 'type': VectorIndex, 'doc': 'test', 'shape': (None,)},
        is_method=False)
def test_func(**kwargs):
    pass

test_func(vec_index=data_ind)
```

```
Traceback (most recent call last):
  File "/Users/bendichter/dev/ndx-point-cloud-table/test_vectorindex.py", line 17, in <module>
    test_func(vec_index=data_ind)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/utils.py", line 451, in func_call
    raise_from(ExceptionType(msg), None)
  File "<string>", line 3, in raise_from
ValueError: incorrect shape for 'vec_index' (got '(2, 2, 3)', expected '(None,)')
```

`np.shape(data_ind)` and `np.shape(data_ind.data)` both yield the correct shape of (2,). Presumably this mistaken shape is due to a `[:]` call on `vec_index` within docval, which not only yields the wrong shape, but also reads the data unnecessarily. This may be a contributing factor to the performance issues we are seeing for @oruebel's icephys extension.

## Environment

    Python Executable: Conda
    Python Version: Python 3.7
    Operating System: macOS

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by ajtritt** [comment]
I don't get that error. I'm on the latest version of dev (55dc7dd2b51f4725bd818fb58eb8d811319279a2)

**Comment by bendichter** [comment]
thanks
