### ISSUE TITLE
get_class for DynamicTable

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#234]
Right now `get_class` is not working for extensions that inherit from the `DynamicTable` class. Writing an extension is pretty involved, requiring you to register a class and a mapper, but the workflow is pretty uniform and we should be able to automate it.

Briefly describe the needed feature as well as the reasoning behind it

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm trying to achieve [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

## Checklist

- [ ] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [ ] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [ ] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
Resolved by #536.
