### ISSUE TITLE
nwb.device.yaml not sorted alphabetically

### ISSUE THREAD

**Issue by ukos-git** [hdmf-dev/hdmf#255]
## Description

All `yaml` spec files are currently sorted alphabetically. This applies to all but the new `nwb.device` spec.

Sorting the keys alphabetically makes it easier for programs to process it.

## Steps to Reproduce

```bash
▶ yq -yS --indentless-lists . core/nwb.device.yaml > temp.yaml
▶ diff --color core/nwb.device.yaml temp.yaml
```

The diff looks like this:

```diff
2,6c2,4
< - neurodata_type_def: Device
<   neurodata_type_inc: NWBContainer
<   doc: Metadata about a data acquisition device, e.g., recording system, electrode, microscope.
<   attributes:
<   - name: description
---
> - attributes:
>   - doc: Description of the device (e.g., model, firmware version, processing software
>       version, etc.) as free-form text.
8,9c6
<     doc: Description of the device (e.g., model, firmware version, processing software version, etc.)
<       as free-form text.
---
>     name: description
11c8
<   - name: manufacturer
---
>   - doc: The name of the manufacturer of the device.
13c10
<     doc: The name of the manufacturer of the device.
---
>     name: manufacturer
14a12,15
>   doc: Metadata about a data acquisition device, e.g., recording system, electrode,
>     microscope.
>   neurodata_type_def: Device
>   neurodata_type_inc: NWBContainer
```

and the proposed yaml for HDMF Version: 1.1.0

```yaml
groups:
- attributes:
  - doc: Description of the device (e.g., model, firmware version, processing software
      version, etc.) as free-form text.
    dtype: text
    name: description
    required: false
  - doc: The name of the manufacturer of the device.
    dtype: text
    name: manufacturer
    required: false
  doc: Metadata about a data acquisition device, e.g., recording system, electrode,
    microscope.
  neurodata_type_def: Device
  neurodata_type_inc: NWBContainer
```

which looks a lot more alike the other specs.

**Comment by rly** [comment]
> All `yaml` spec files are currently sorted alphabetically. This applies to all but the new `nwb.device` spec.

@ukos-git Looking through the spec files, it seems that none of our yaml spec files are sorted alphabetically. Am I missing something?

While sorting the keys alphabetically makes it easier for programs to process it, we insist that the YAML spec files are human-readable and intuitively organized. Thus, we have imposed our own ordering - see https://github.com/NeurodataWithoutBorders/nwb-schema/issues/274

**Comment by bendichter** [comment]
@ukos-git the yaml files used to be sorted alphabetically, but we changed that long ago because it was difficult for humans (e.g. me) to read. Is there a particular reason you would like them to be alphabetical?

**Comment by ukos-git** [comment]
I just realized that indeed the files are not sorted in the current schema. (And that I should have opened this at nwb-schema)

I was updating a lot of our specifications in IPNWB and needed to look at the diffs to compare the changes. For that reason I was sorting to see the diff better.

Thanks for the feedback.

#Close

**Comment by bendichter** [comment]
@rly maybe we could add our preferred order to the spec language doc or to
the best practices doc.
