### ISSUE TITLE
1.5.0 tests.unit.common.test_table.TestDynamicTableRoundTrip fails on some platforms

### ISSUE THREAD

**Issue by yarikoptic** [hdmf-dev/hdmf#256]
built neurodebian package for hdmf, and it failed that test on all but most recent debian sid/bullseye:
```
hdmf_1.5.1-1~nd80+1_amd64.build FAILED  0:15.11 real, 11.12 user, 4.49 sys, 101728 out
hdmf_1.5.1-1~nd90+1_amd64.build FAILED  0:49.21 real, 39.93 user, 13.79 sys, 808928 out
hdmf_1.5.1-1~nd100+1_amd64.build        FAILED  1:04.23 real, 59.61 user, 16.91 sys, 864600 out
hdmf_1.5.1-1~nd110+1_amd64.build        OK      1:24.23 real, 79.49 user, 21.88 sys, 1183048 out
hdmf_1.5.1-1~nd+1_amd64.build   OK      1:32.47 real, 85.06 user, 25.61 sys, 1217472 out
hdmf_1.5.1-1~nd14.04+1_amd64.build      FAILED  0:54.43 real, 40.21 user, 18.00 sys, 112232 out
hdmf_1.5.1-1~nd16.04+1_amd64.build      FAILED  1:24.55 real, 64.63 user, 25.81 sys, 734224 out
hdmf_1.5.1-1~nd18.04+1_amd64.build      FAILED  1:35.20 real, 79.69 user, 29.11 sys, 790376 out
hdmf_1.5.1-1~nd18.10+1_amd64.build      FAILED  1:43.95 real, 90.95 user, 31.98 sys, 1023984 out
hdmf_1.5.1-1~nd19.04+1_amd64.build      FAILED  1:38.25 real, 83.20 user, 30.04 sys, 832480 out

```
the failure seems to be the same:
```
======================================================================
ERROR: test_roundtrip (tests.unit.common.test_table.TestDynamicTableRoundTrip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/hdmf-1.5.1/.pybuild/cpython3_3.7_hdmf/build/hdmf/testing/testcase.py", line 164, in test_roundtrip
    self.read_container = self.roundtripContainer()
  File "/build/hdmf-1.5.1/.pybuild/cpython3_3.7_hdmf/build/hdmf/testing/testcase.py", line 178, in roundtripContainer
    self.writer.write(self.container, cache_spec=cache_spec)
  File "/build/hdmf-1.5.1/.pybuild/cpython3_3.7_hdmf/build/hdmf/utils.py", line 440, in func_call
    return func(self, **parsed['args'])
  File "/build/hdmf-1.5.1/.pybuild/cpython3_3.7_hdmf/build/hdmf/backends/hdf5/h5tools.py", line 269, in write
    call_docval_func(super().write, kwargs)
  File "/build/hdmf-1.5.1/.pybuild/cpython3_3.7_hdmf/build/hdmf/utils.py", line 330, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/build/hdmf-1.5.1/.pybuild/cpython3_3.7_hdmf/build/hdmf/utils.py", line 440, in func_call
    return func(self, **parsed['args'])
  File "/build/hdmf-1.5.1/.pybuild/cpython3_3.7_hdmf/build/hdmf/backends/io.py", line 44, in write
    self.write_builder(f_builder, **kwargs)
  File "/build/hdmf-1.5.1/.pybuild/cpython3_3.7_hdmf/build/hdmf/utils.py", line 440, in func_call
    return func(self, **parsed['args'])
  File "/build/hdmf-1.5.1/.pybuild/cpython3_3.7_hdmf/build/hdmf/backends/hdf5/h5tools.py", line 541, in write_builder
    self.set_attributes(self.__file, f_builder.attributes)
  File "/build/hdmf-1.5.1/.pybuild/cpython3_3.7_hdmf/build/hdmf/utils.py", line 440, in func_call
    return func(self, **parsed['args'])
  File "/build/hdmf-1.5.1/.pybuild/cpython3_3.7_hdmf/build/hdmf/backends/hdf5/h5tools.py", line 658, in set_attributes
    obj.attrs[key] = value
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/lib/python3/dist-packages/h5py/_hl/attrs.py", line 95, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/usr/lib/python3/dist-packages/h5py/_hl/attrs.py", line 171, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py/h5t.pyx", line 1611, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1633, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1694, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U3')
```
you could find all build logs at http://neuro.debian.net/_files/_buildlogs/hdmf/1.5.1, but here is versions for most obvious suspects:

bad:
```
neurodebian@smaug ~/deb/builds/hdmf/1.5.1-1 % grep 'Unpacking python3-\(numpy\|h5py\)' hdmf_1.5.1-1~nd100+1_amd64.build                                                                                                       :(
Unpacking python3-numpy (1:1.16.2-1) ...
Unpacking python3-h5py (2.8.0-3) ...
```
good/recent:
```
neurodebian@smaug ~/deb/builds/hdmf/1.5.1-1 % grep 'Unpacking python3-\(numpy\|h5py\)' hdmf_1.5.1-1~nd110+1_amd64.build
Unpacking python3-numpy (1:1.17.4-5) ...
Unpacking python3-h5py (2.10.0-2+b1) ...

```

NB I am having déjà vu of seeing similar issue, but can't find it in pynwb or hdmf issues, must have happened elsewhere

**Comment by rly** [comment]
Thanks @yarikoptic . Any chance you can re-run the tests using the latest pre-release (git tag: latest) or equivalently, the dev branch, on one of the broken platforms?

**Comment by rly** [comment]
We have pinned the HDMF requirements to the following versions:
```
h5py==2.10.0
numpy==1.18.1
```
Are your builds ignoring those requirements? Also, it looks like pinning is not done for conda just yet.

If my guess is correct, the error was introduced in https://github.com/hdmf-dev/hdmf-common-schema/pull/5 when the 'colnames' attribute of a `DynamicTable` was changed from "ascii" to "text" in order to support utf-8 encoding. Prior to h5py 2.9, attributes could not be set to lists of unicode strings. This appears to have been fixed with this PR: https://github.com/h5py/h5py/pull/1032 and was released in h5py 2.9.

**Comment by yarikoptic** [comment]
> Are your builds ignoring those requirements?

Yes.  For any Linux distribution  hard pinning is not an acceptable practice. And in general hard pinning (in particular for libraries) is not advised strategy. E.g. by pinning to h5py and numpy of specific version you forbid users to take advantage of bug fixes which were introduced by later versions of those dependencies. A bit more on the common practice as I see it - see https://github.com/NeurodataWithoutBorders/pynwb/issues/1133#issuecomment-571764474  .


> This appears to have been fixed with this PR: [h5py/h5py#1032](https://github.com/h5py/h5py/pull/1032) and was released in h5py 2.9.

So, if you would feel that it is the requirement, then `install_requires` in `setup.py` should have `h5py >= 2.9`, which would then be enforced when users do `python setup.py install` on hdmf. And indeed that would explain it since all those distributions where it failed only have an earlier version available:
```shell 
neurodebian@smaug ~/deb/builds/hdmf/1.5.1-1 % grep 'Unpacking python3-h5py' *build                                  
hdmf_1.5.1-1_amd64.build:Unpacking python3-h5py (2.10.0-2+b1) ...
hdmf_1.5.1-1~nd100+1_amd64.build:Unpacking python3-h5py (2.8.0-3) ...
hdmf_1.5.1-1~nd110+1_amd64.build:Unpacking python3-h5py (2.10.0-2+b1) ...
hdmf_1.5.1-1~nd16.04+1_amd64.build:Unpacking python3-h5py (2.6.0-1) ...
hdmf_1.5.1-1~nd18.04+1_amd64.build:Unpacking python3-h5py (2.7.1-2) ...
hdmf_1.5.1-1~nd18.10+1_amd64.build:Unpacking python3-h5py (2.8.0-1) ...
hdmf_1.5.1-1~nd19.04+1_amd64.build:Unpacking python3-h5py (2.8.0-3) ...
hdmf_1.5.1-1~nd+1_amd64.build:Unpacking python3-h5py (2.10.0-2+b1) ...
hdmf_1.5.1-1~nd90+1_amd64.build:Unpacking python3-h5py (2.7.1-2~nd90+1) ...
```
I will see if there is an easy way to backport 2.10 to those older debian/ubuntu releases.

I would have "closed" this issue by making sure that `setup.py` provides proper minimal (not specifically pinned) version of `h5py` required by hdmf.

**Comment by rly** [comment]
@yarikoptic Thanks for the feedback. Yes, that all makes sense. Since I cannot test all possible combinations of previous versions of our dependencies, what is the recommended strategy / best practice for setting minimal versions in `setup.py` and doing continuous integration? Should we adjust the minimum versions only when we know an earlier version is incompatible (e.g., through reading release notes or bug reports)? Should we pre-emptively set minimum versions for all requirements based on a few tests like I have done in #258? Should we have a CI job that runs tests using the minimum versions of all requirements?

**Comment by yarikoptic** [comment]
> what is the recommended strategy / best practice for setting minimal versions in `setup.py` and doing continuous integration?

Typically we (so YMMV) boost minimal version requirement in setup.py when we detect the need for more recent version. See e.g. https://github.com/datalad/datalad/blob/master/setup.py#L27 or a more "modern" way via setup.cfg in nibabel: https://github.com/nipy/nibabel/blob/master/setup.cfg#L30 .
CI: we typically test with whatever versions (system wide or from pypi, could be newer than we ever tried) are available and satisfy those requirements.

> Should we adjust the minimum versions only when we know an earlier version is incompatible (e.g., through reading release notes or bug reports)?

yes, something like that.  Or just seeing (getting a bug report) that some test fails on some systems.
 Also, for datalad, we test datalad against new releases of git-annex (and bundled in that package git), before uploading that new git-annex to neurodebian -- so we know that in our most common way to deploy it (neurodebian) we do not have git-annex with regressions and/or incompatible with datalad (and that is why haven't uploaded a new git annex now for a few months -- still fighting to regain stable combination).  Since git-annex is an external tool, we also run a check for its version, and annotate our "minimal version requirement" reasons: https://github.com/datalad/datalad/blob/master/datalad/support/annexrepo.py#L125  

> Should we pre-emptively set minimum versions for all requirements based on a few tests like I have done in #258? 

that pr looks good.  I had in a few cases to submit PRs to projects to downgrade their minimal requirement where it was just set because "I tested with this version, and simply don't know about previous ones".  You might benefit from adding comment against each one, like we do for git-annex, annotating why this particular version, e.g.
```
        'h5py>=2.9',  # utf8 support, we test it
```
which would make it clear why this particular one.  I should start doing such annotations more myself ;)

> Should we have a CI job that runs tests using the minimum versions of all requirements?

that would be real nice!  I must say we never did it (our datalad tests already include many matrix runs and take awhile already), but it makes total sense.  It would probably be a bit pain to maintain both minimal versions in `setup.py` and possibly them pinned in `requirements.txt`.  So may be your approach of parsing `requirements.txt` could be used and just converting `==` into `>=` or smth like that.  not sure yet if/when it would break.

**Comment by yarikoptic** [comment]
oh, and just a wishlist from yours truly: if you don't know what minimal version to choose -- consider the ones available in Debian stable (or even oldstable): could be found via search on https://www.debian.org/distrib/packages. If they are "not good" - that is life, but if they work -- it would simplify my backport builds for neurodebian.

**Comment by rly** [comment]
Thanks @yarikoptic . HDMF 1.5.3 contains some minimum requirements for the package dependencies. It looks like all versions except h5py 2.9 are found in Debian stable. Let me know if any version requirements should be relaxed. I think we can close this now.

**Comment by yarikoptic** [comment]
coolio, I will build updated package for hdmf... what is ETA for pynwb release? ;)

**Comment by rly** [comment]
Either tomorrow or Tuesday.

**Comment by yarikoptic** [comment]
Cool, thanks!
