### ISSUE TITLE
files with external links cannot be read in append mode

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#26]
## Bug

```python
from pynwb import NWBFile, TimeSeries, get_manager, NWBHDF5IO
from datetime import datetime
from dateutil.tz import tzlocal

fpath = 'test_externals.nwb'
fpath2 = 'test_externals2.nwb'

manager = get_manager()

nwbfile = NWBFile("a file with header data", "NB123A", datetime(2017, 5, 1, 12, 0, 0, tzinfo=tzlocal()))

nwbfile.add_acquisition(TimeSeries('ts_name', data=[1,2,3], unit='m', rate=100.))


with NWBHDF5IO(fpath, mode='w', manager=manager) as io:
    io.write(nwbfile)

nwbfile2 = NWBFile("a file with header data", "NB123B", datetime(2017, 5, 1, 12, 0, 0, tzinfo=tzlocal()))

nwb_read = NWBHDF5IO(fpath, mode='r', manager=manager).read()

nwbfile2.add_acquisition(nwb_read.acquisition['ts_name'])

with NWBHDF5IO(fpath2, mode='w', manager=manager) as io:
    io.write(nwbfile2)

with NWBHDF5IO(fpath2, mode='a') as io:
    io.read()
```

error:
```python
Traceback (most recent call last):
  File "/Users/bendichter/Library/Preferences/PyCharmCE2019.1/scratches/scratch_22.py", line 29, in <module>
    io.read()
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/backends/io.py", line 32, in read
    f_builder = self.read_builder()
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 227, in read_builder
    f_builder = self.__read_group(self.__file, ROOT_NAME, ignore=ignore)
  File "/Users/bendichter/dev/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 304, in __read_group
    builder = read_method(sub_h5obj)
  File "/Users/bendichter/dev/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 272, in __read_group
    if sub_h5obj.name in ignore:
AttributeError: 'NoneType' object has no attribute 'name'
```
Please describe your environment according to the following bullet points.

    Python Executable: Conda
    Python Version: Python 3.6
    Operating System: macOS
    HDMF Version: dev

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment]
the error was a bit m misleading but the issue was I had the file open in another location

**Comment by bendichter** [comment]
This file has an extension which is also an external link. I suspect this error is due to the fact that it has an external link

**Comment by bendichter** [comment]
I think the issue is around build/map.py line 1579: `attr_map.construct(builder, build_manager)`. builder has a non-`None` parent, but the output of this line has `parent==None`. From here I think the issue is in `ObjectMapper`, but I'm not sure.

**Comment by bendichter** [comment]
@ajtritt could you help me out with this?

**Comment by bendichter** [comment]
@ajtritt Do you have any intuitions how we might fix this?

**Comment by rly** [comment]
@bendichter There are several related issues here, and I am working on creating tickets and PRs for each. The first is that, unfortunately, h5py cannot access an ExternalLink if it is open elsewhere. 

http://docs.h5py.org/en/stable/high/group.html:
> Currently, you can’t access an external link if the file it points to is already open. This is related to how HDF5 manages file permissions internally.

So, try changing the middle part of your example code to the following:
```
with NWBHDF5IO(fpath, mode='r', manager=manager) as io:
    nwb_read = io.read()
    nwbfile2.add_acquisition(nwb_read.acquisition['ts_name'])
    io.close()
```

In my setup, opening `nwbfile2` in append mode now works.

**Comment by rly** [comment]
A nicer warning should be issued if this situation is detected.

**Comment by bendichter** [comment]
yeah, this works! Thanks!
