### ISSUE TITLE
namespace version

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#275]
the `version` arg of `NamespaceBuilder` should be required. It isn't 100% clear for the specification-language documentation whether version is required, but it should be. Some groups have been writing NWB files with uncached, unversioned, unregistered extensions and I am concerned this will cause problems. The least we can do is require that the extensions are versioned.

**Comment by rly** [comment]
The AIBS extension is a good example: https://github.com/AllenInstitute/AllenSDK/blob/master/allensdk/brain_observatory/ecephys/nwb/AIBS_ecephys_namespace.yaml

I am in favor of this. We could add a check in the constructor and raise a warning, e.g.,:
```python
if getargs('version', kwargs) is None:
    warnings.warn("The 'version' argument will not be optional in a future version. Please provide a 'version'.", FutureWarning)
```

Or we could raise an error instead. A warning would be backwards compatible. But I kinda think it is a bug that `version` is optional and so raising an error is OK. Thoughts?

The same change has to be made in `NWBNamespaceBuilder` in PyNWB.

**Comment by bendichter** [comment]
I think this is one of those cases where *technically* breaking backwards compatibility is justified. I'd rather throw and error and force people to include a version, since I see this as fixing a bug rather than adding a new feature. Though if others disagree I think a warning would be a big improvement over the current state.

**Comment by t-b** [comment]
Error!

**Comment by bendichter** [comment]
side node: why can version be a tuple or a list? I would think it should just be a string

**Comment by rly** [comment]
@bendichter I don't know. I think it should also be a string.

**Comment by bendichter** [comment]
changing the accepted types to just `str` doesn't break any tests. Still, I'm sure there must have been some reason to do this. @ajtritt, do you know?

**Comment by oruebel** [comment]
> why can version be a tuple or a list

I believe in the YAML files it is a string. In the constructor it is allowed to be a tuple of ints to allow more explicit definition of major/minor version (i.e., (``1,2,0)`` instead of ``'1.2.0'``). 

> I'd rather throw and error

I agree that throwing an error is the right way to go here.
