### ISSUE TITLE
Spec language does not support generic string type

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#281]
In the [spec language](https://schema-language.readthedocs.io/en/latest/specification_language_description.html#dtype), there is a dtype for a generic numeric type "numeric". It would also be useful to have a dtype for a string that could be represented as either utf8 or ascii. For whatever reason, the string "text" is already used as a synonym for "utf8". We could make "text" a generic type that encompasses both utf8 and ascii. What do you think, @ajtritt @oruebel ? 

This is relevant because https://github.com/hdmf-dev/hdmf-common-schema/pull/5/files changed the dtype of `DynamicTable.colnames` from "ascii" to "text". As a result, NWB 2.2 files do not conform to NWB 2.1, and NWB 2.1 files do not conform to NWB 2.2. Changing the definition of "text" would at least make NWB 2.1 files conform to NWB 2.2.

**Comment by t-b** [comment]
Yes the `DynamicTable.colnames` changed from `ascii` to `text`. But why  does that invalidate old files? The available characters for the text got more and not less so all old `ascii` encoded text is also valid `utf8`.

**Comment by rly** [comment]
Ah, I forgot that valid ASCII text is valid UTF-8-encoded Unicode as well.

**Comment by rly** [comment]
Interestingly, this is different from how we use minimum precision for numeric values currently. If a spec says "int16", then an int16, int32, or int64 value may be provided. "int8" is not allowed, even though, in theory an 8-bit integer can be cast into a 16-bit integer. 

Here, we say, if a spec says "utf8", then an UTF-8 (8-bit encoding) or an ASCII (7-bit encoding) string may be provided because an ASCII string can be cast into an UTF-8 string.

**Comment by oruebel** [comment]
> Interestingly, this is different from how we use minimum precision for numeric

I think this is a false equivalency. E.g., if we specify ``int16`` as data type, that does not mean that the data has to actually use the full range of values that int16 supports, but if your data just consists of values ``1,2,3``, that's perfectly fine. Similarly here, since ASCII is a subset of UTF-8 it is fine to use just the ASCII part of UTF-8 when writing text.
