### ISSUE TITLE
Include object name in UserWarning "Value with data type x is being converted to y"

### ISSUE THREAD

**Issue by lvsltz** [hdmf-dev/hdmf#306]
Follow up on #298 

Now I do get a warning like this one on write... but have no clue where it's coming from. 
I think the warning message should also contain the object to which it refers.
```python
./miniconda3/envs/nwb_latest/lib/python3.7/site-packages/hdmf/build/objectmapper.py:146:
UserWarning: Value with data type int64 is being converted to data type uint64
(min specification: uint32).
  % (g.name, ret_type.name, s.name))
```

**Comment by rly** [comment]
@lvsltz I made a PR to fix this issue. #311

The culprit of your situation is likely the sweep number, which is one of the few types that are specified as a uint. You can wrap your integer with `np.uint` to fix that. Perhaps `pynwb.icephys.PatchClampSeries` should be changed to cast the sweep number to uint if it can tell that the type is not a uint.
