### ISSUE TITLE
Cannot extend group with subgroup/dataset that contains type definition

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#316]
This issue is revealed in https://github.com/oruebel/ndx-icephys-meta/issues/21.

The new `ICEphysFile` type extends the `NWBFile` type. The namespace containing the new type cannot be loaded with `load_namespaces`, e.g., during validation or `NWBHDF5IO(filename, 'r', load_namespaces=True)` because:
1) the `Subject` subgroup of `NWBFile/general/` defined with `NWBFile` is not detected as an inherited data type because it has a name, and 
2) the `ScratchData` dataset defined with `NWBFile` is not detected as an inherited data type because it does not have a name.

The source of the problem seems to be `GroupSpec.resolve_spec` which determines whether a child group/dataset/link spec is inherited, overrides an inherited spec, or is new. 

One way to get around the problem is to disallow extension of types with nested type definitions. i.e. move the definition of `Subject` and `ScratchData` outside the definition of `NWBFile`. It would also have the benefit of removing the possibility of these edge cases which are difficult to maintain and test for and may cause other issues. 

Defining a new type within an existing type tells users where the new type is *intended* to be used, but it does not enforce that (I can add a Subject to /acquisition if I want) and it adds a lot of complexity, so I would prefer to remove all cases in the NWB schema where this occurs. See related issue: https://github.com/hdmf-dev/hdmf/issues/73

Alternatively, we could change the logic of `GroupSpec.resolve_spec` to handle these edge cases better, but that is proving quite difficult. @ajtritt I could use your help and feedback on this.

**Comment by rly** [comment]
The resolution from our video chat discussion was to remove all cases in the NWB schema where this occurs and raise an error if an extension tries to do this.

**Comment by oruebel** [comment]
Just for clarification, this does not change the actual schema, it just moves nested type definitions to the top level and includes them in the appropriate places. This is a best-practice anyways, so this is just cleaning up the schema files.

**Comment by rly** [comment]
This issue has been resolved as described above.
