### ISSUE TITLE
Build process is inefficient and sometimes inaccurate for links and references

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#337]
Using the new logging code, I found that during the build process, a `Container` is rebuilt every time it is linked to or referenced. This is quite inefficient, especially when the file contains lots of tables and links between them, like in the [icephys-meta extension](https://github.com/oruebel/ndx-icephys-meta/). 

The cuplrit is this section in `BuildManager.build`:
https://github.com/hdmf-dev/hdmf/blob/7d5ec7b08b742069c24b9622cbbb4a29fea96935/src/hdmf/build/manager.py#L165-L171

The `Builder` is loaded from the `prebuilt` variable but because `Container.modified` is True, `type_map.build` is called. This happens when the Container is built at its place in the container hierarchy and every time a link or reference to that Container is made.

**Comment by oruebel** [comment]
Thanks for tracing down this bug. This is indeed a very likely source for the slow performance we have seen on write for the icephys extension.
