### ISSUE TITLE
hdmf.__version__ fails

### ISSUE THREAD

**Issue by tbenst** [hdmf-dev/hdmf#344]
## Description

I'm having an issue with the latest version of hdmf that doesn't exist on a previous version. I'm having a hard time troubleshooting as this fails:

## Steps to Reproduce

```
>>> import hdmf
>>> hdmf.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'hdmf' has no attribute '__version__'
```

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
Thanks. This will be fixed in #345
