### ISSUE TITLE
Cannot construct some extension types if type ancestry is not included in namespace

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#356]
## Description

I am deep in the world of extensions for several groups. 

If an extension:
1) defines a type that does not directly extend `NWBDataInterface` (e.g., it extends `ElectricalSeries`)
2) the namespace includes the extended type (e.g., `ElectricalSeries`)
3) the namespace does not include the ancestry of the extended type all the way back to `NWBDataInterface`,

then when I add an instance of that type to `nwbfile.acquisition` (which allows `NWBDataInterface` objects), write the NWB file, and then read the file, the build process does not construct the new type. 

For example, if I define a new type `TetrodeSeries` that extends `ElectricalSeries` and the namespace file includes only the `ElectricalSeries` type from pynwb core, then the `TetrodeSeries` objects in `nwbfile.acquisition` will not be constructed from file.

However, if the namespace DOES include the ancestry of the extended type all the way back to `NWBDataInterface`, e.g., the extension namespace file includes the following:
```yaml
  schema:
  - namespace: core
    neurodata_types:
    - ElectricalSeries
    - TimeSeries
    - NWBDataInterface
```

then the build process works correctly.

I think including JUST the extended type, e.g., `ElectricalSeries`, should be sufficient to achieve the desired behavior, and this is a bug. Thoughts @ajtritt @oruebel ?

**Comment by ajtritt** [comment]
> I think including JUST the extended type, e.g., ElectricalSeries, should be sufficient to achieve the desired behavior, 

Sure, that makes sense. The simplest solution to me would be to include all parent data_types of an included data_type.

**Comment by oruebel** [comment]
I agree, it sounds like the best way is to include parent types when including a given type.

**Comment by rly** [comment]
Great. Thanks for the input!

**Comment by rly** [comment]
I am pinging this (to myself) because the Allen Institute devs ran into this issue today. 

Related: Writing extended data types that are missing the included hierarchy fails silently. An error should be raised.
