### ISSUE TITLE
HDF5IO should be able to take only File object

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#366]
Right now, when you call HDF5IO, you can supply a File object, but you also need to specify a path, the code files if the filename of the object does not match the path. It does not make much sense to me why you would need to specify both the path and the File object. One or the other should be enough

**Is your feature request related to a problem? Please describe.**
I am trying to read an HDF5 file on S3 using [s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse). I have made the adjustments to hdmf and pynwb to confirm that this will work, we just need to make this modification, because in this case I have a File object but no local 'path'.

**Describe the solution you'd like**
I would like to change this so that you can enter a file arg and no path arg. In order for this to work, both the `path` and the `mode` arguments will need to become optional.

**Comment by rly** [comment]
Fixed by #746.
