### ISSUE TITLE
Adding optional predefined column should raise warning not error

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#370]
## Description

With PR #305, adding a column that is an optional column defined in `__columns__` raises an error. However, this new error breaks existing code such as in the AllenSDK: https://travis-ci.org/github/AllenInstitute/AllenSDK/jobs/692971698
where they get the error: `ValueError: column 'spike_times' already exists in Units 'units'` after calling `Units.add_column`. This had previously worked for optional columns without complaint.

Raising this error is a breaking change on code that is not clearly wrong and so should be changed to a warning until the next major version. Users should also be able to add a predefined optional column with a different description than the default supplied by PyNWB, if desired (the column description is typically not specified in the NWB spec).

## Steps to Reproduce

```python
from hdmf.common import DynamicTable


class SubTable(DynamicTable):

    __columns__ = (
        {'name': 'col2', 'description': 'optional column', 'required': False},
    )


table = SubTable(name='subtable', description='subtable description')
table.add_column('col2', 'column #2')
```
## Environment

    Python Executable: Python
    Python Version: Python 3.7
    Operating System: Windows
    HDMF Version: dev

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
Making this error a warning raises the following issue. What if the user-specified column does not match the API-predefined column? Some basic checks should be made on whether the column is indexed or is a table region, so that the code does not fail when writing a mismatched optional column to disk and does not fail during validation.

**Comment by njmei** [comment]
@rly Thanks for creating and working on this issue!
