### ISSUE TITLE
keep child info in __fields__

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#440]
see https://github.com/NeurodataWithoutBorders/pynwb/issues/1304

We'd like to be able to determine if an argument is destined to be a link or not, but the 'child' fields in `cls.__field__` are currently overwritten, so there is no way to determine this from the API

**Comment by rly** [comment]
@bendichter you can now use `AbstractContainer.get_fields_conf()` to get the field configuration values from `__fields__` in a normalized form - a tuple of dictionaries (strings are converted to dicts). To get whether the field is a child, you can use something like:
```python
children_fields = [f['name'] for f in MyClass.get_fields_conf() if getattr(f, 'child', False)]
```
