### ISSUE TITLE
Provide more informative warnings if a link is broken

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#45]
Enhancement
---

If an external link is broken, currently the user gets a warning message such as the following:
```
c:\users\ryan\documents\nwb\hdmf\src\hdmf\backends\hdf5\h5tools.py:306: UserWarning: Broken Link: /acquisition\acquisition
  warnings.warn('Broken Link: %s' % os.path.join(h5obj.name, k))
c:\users\ryan\documents\nwb\hdmf\src\hdmf\backends\hdf5\h5tools.py:306: UserWarning: Broken Link: /acquisition\ts_name
  warnings.warn('Broken Link: %s' % os.path.join(h5obj.name, k))
```
Suggestion: the warning should say whether the link is broken because 
- the file is open elsewhere (see #26), or
- the file cannot be found, or
- the path within the file cannot be found

User should also not get **two** warnings when there is only one broken link.

Unit tests should test these warnings as well.

Steps to Reproduce
---

```python
from pynwb import NWBFile, TimeSeries, get_manager, NWBHDF5IO
from datetime import datetime
from dateutil.tz import tzlocal
import os

fpath = 'test_externals.nwb'
fpath2 = 'test_externals2.nwb'

manager = get_manager()

nwbfile = NWBFile("a file with header data", "NB123A", datetime(2017, 5, 1, 12, 0, 0, tzinfo=tzlocal()))
nwbfile.add_acquisition(TimeSeries('ts_name', data=[1,2,3], unit='m', rate=100.))

with NWBHDF5IO(fpath, mode='w', manager=manager) as io:
    io.write(nwbfile)
    io.close()

nwbfile2 = NWBFile("a file with header data", "NB123B", datetime(2017, 5, 1, 12, 0, 0, tzinfo=tzlocal()))

with NWBHDF5IO(fpath, mode='r', manager=manager) as io:
    nwb_read = io.read()
    nwbfile2.add_acquisition(nwb_read.acquisition['ts_name'])
    io.close()

with NWBHDF5IO(fpath2, mode='w', manager=manager) as io:
    io.write(nwbfile2)
    io.close()

os.remove(fpath)

with NWBHDF5IO(fpath2, mode='r') as io:
    nwbfile3 = io.read()
    io.close()
```

Environment
---

    Python Executable: Conda
    Python Version: Python 3.6
    Operating System: Windows
    HDMF Version: 1.0.3

**Comment by mavaylon1** [comment]
@rly Running the code above now just returns one error. I'll look into the unit testing to see if anything was updated there. Otherwise is there anything else?

Update: I don't see anything in test_io_hdf5.py that tests this warning. I'll make one.

**Comment by rly** [comment]
I think that's it. Add unit tests and improve the warning message.
