### ISSUE TITLE
target_type in Spec constructors should take GroupSpec and DatasetSpec

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#464]
Briefly describe the needed feature as well as the reasoning behind it

**Is your feature request related to a problem? Please describe.**
`GroupSpec.data_type_inc` takes a `GroupSpec` object or a string, and `DatasetSpec.data_type_inc` takes a `DatasetSpec` object or a string. Currently, `LinkSpec.target_type` takes only a string, but to be consistent,  it should take a string, a `GroupSpec`, or a `DatasetSpec`.

**Comment by bendichter** [comment]
It's not as easy as adding this to the docval of `LinkSpec`. Doing that will put the entire `GroupSpec` definition into the link object, when all you want is to reference it by name

**Comment by rly** [comment]
I'm on it
