### ISSUE TITLE
Add pre-release tests

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#471]
The h5py 3.0 issue sort of caught us off-guard. Satra had a recommendation for how we might be able to get out ahead of changes to our dependencies in the future with pre-release tests. You can pip install with a "-pre" flag, which searches pypi for "rc" (release candidates) for our dependencies and installs those instead. The idea would be to run these tests along with the others, but to not make their passing a requirement of merging PRs. This way we can be informed about what changes are coming to our dependencies and be ready for them before they drop.

**Comment by rly** [comment]
Nice idea. Rather than put that as a test on CI for PRs, where they will slow down PRs and kind of look bad, we could include it as a test on our nightly CI, which we are currently using to test builds on Python 3.9. We get nightly emails with the status of those CI tests.

**Comment by bendichter** [comment]
Yeah, that sounds even better!
