### ISSUE TITLE
Add duecredit support

### ISSUE THREAD

**Issue by yarikoptic** [hdmf-dev/hdmf#476]
To be able to track for citation and versioning purposes: https://github.com/duecredit/duecredit/

Ref: https://github.com/dandi/dandi-cli/issues/57#issuecomment-733780222 

So what would be the canonical citation for hdmf?

**Comment by rly** [comment]
Interesting idea. Here is the canonical citation for HDMF:

doi:10.1109/BigData47090.2019.9005648
https://ieeexplore.ieee.org/document/9005648
bibtex:
```bibtex
@INPROCEEDINGS{9005648,
  author={A. J. {Tritt} and O. {Rübel} and B. {Dichter} and R. {Ly} and D. {Kang} and E. F. {Chang} and L. M. {Frank} and K. {Bouchard}},
  booktitle={2019 IEEE International Conference on Big Data (Big Data)}, 
  title={HDMF: Hierarchical Data Modeling Framework for Modern Science Data Standards}, 
  year={2019},
  volume={},
  number={},
  pages={165-179},
  doi={10.1109/BigData47090.2019.9005648}}
```

**Comment by oruebel** [comment]
@rly I'd suggest to add the citation to the README.md

**Comment by rly** [comment]
After tackling a Windows-specific bug in a dependency, this was pretty easy to implement in #488 and looks non-disruptive.
