### ISSUE TITLE
Remove impossible to reach code in validator

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#479]
It is not possible to reach lines 468-477 in `validator.py`: https://github.com/hdmf-dev/hdmf/blob/dev/src/hdmf/validate/validator.py#L468-L477

`self.__dataset_validators` and `self.__group_validators` can only ever contain `GroupValidator` and `DatasetValidator` types, never `BaseStorageSpec` types. @ajtritt it looks like you wrote this code years ago. Do you remember why it is there or its intention? Can it be removed?

This comes up because #478 involves a change to code there, and this code chunk will confuse developers and create unnecessary upkeep in the future.

**Describe the solution you'd like**
Remove these lines and the if statement.

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by ajtritt** [comment]
Not sure how that got in there, it could be vestigial or the result of writing code on an airplane. I'm fine to remove it.
