### ISSUE TITLE
get_class, supplied name

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#48]
Bug

It is possible to define a class and lock it to a specific name:

```python
from pynwb.spec import NamespaceBuilder, NWBGroupSpec

name = 'single_dataset'
doc = 'example extension for single dataset'

ns_builder = NamespaceBuilder(doc=doc, name=name, version='0.1',
                              author=['author'],
                              contact='email')

ns_builder.include_type('LabMetaData', namespace='core')

meta_data = NWBGroupSpec(neurodata_type_inc='LabMetaData', neurodata_type_def='SimulationMetaData', doc='doc',
                         name='simulation_metadata')
meta_data.add_attribute(name='help', doc='doc', dtype='text', default_value='help text here')
dataset = meta_data.add_dataset(name='pin', doc='doc', dtype='float', shape=(None, 12), dims=('runs', 'params'))
dataset.add_attribute(name='help', doc='doc', dtype='text', default_value='help text here')


ns_path = name + '.namespace.yaml'
ext_source = name + '.extensions.yaml'

# Export
for neurodata_type in [meta_data]:
    ns_builder.add_spec(ext_source, neurodata_type)
ns_builder.export(ns_path, outdir='spec')
```

however the class generated by `get_class` still requires a name argument:

```python
from pynwb import NWBHDF5IO, NWBFile, load_namespaces, get_class
from datetime import datetime
import numpy as np


nwbfile = NWBFile('aa', 'aa', datetime.now().astimezone())

load_namespaces('/Users/bendichter/dev/to_nwb/to_nwb/ndx_single_dataset/spec/single_dataset.namespace.yaml')

sim_meta_data = get_class('SimulationMetaData', 'single_dataset')

meta_data = sim_meta_data(pin=np.random.randn(1000, 12))
```

```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/hdmf/issue_910_2.py", line 12, in <module>
    meta_data = sim_meta_data(pin=np.random.randn(1000, 12))
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 386, in func_call
    raise_from(ExceptionType(msg), None)
  File "<string>", line 3, in raise_from
TypeError: missing argument 'name'
```
Although this parameter is unused. The spec name is used, not the supplied name:

```python
from pynwb import NWBHDF5IO, NWBFile, load_namespaces, get_class
from datetime import datetime
import numpy as np

nwbfile = NWBFile('aa', 'aa', datetime.now().astimezone())

load_namespaces('/Users/bendichter/dev/to_nwb/to_nwb/ndx_single_dataset/spec/single_dataset.namespace.yaml')

sim_meta_data = get_class('SimulationMetaData', 'single_dataset')

meta_data = sim_meta_data(name='simulation_params', pin=np.random.randn(1000, 12))
nwbfile.add_lab_meta_data(meta_data)

with NWBHDF5IO('test_a.nwb', 'w') as io:
    io.write(nwbfile, cache_spec=True)


with NWBHDF5IO('test_a.nwb', 'r') as io:
    nwb2 = io.read()
    print(nwb2.lab_meta_data['simulation_metadata'].pin[:])
```

Environment

Please describe your environment according to the following bullet points.

    Python Executable: Conda
    Python Version: Python 3.6
    Operating System: macOS
    HDMF Version: latest

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
I think the code works mostly as intended, but it is certainly not intuitive to the user. Setting the `name` argument on `NWBGroupSpec(...)` will force all objects of the `LabMetaData` type to have the specified name. Setting the `default_name` argument will give all objects of the `LabMetaData` type to have the specified name only if it is not explicitly provided. I think that's why `default_name` is there but maybe I am missing something. 

It's probably rare that you would actually want to set `name` and force all objects to have that name, but maybe the extension writer wants to standardize the name of the group so that `nwb2.lab_meta_data['simulation_metadata']` always works.

If this is intended behavior, however, this:
`meta_data = sim_meta_data(name='simulation_params', pin=np.random.randn(1000, 12))`
should throw an error or something, and the documentation should clearly spell out what setting `name` would do, as opposed to setting `default_name`.

**Comment by bendichter** [comment]
Yeah it's that last part that's the bug

**Comment by oruebel** [comment]
``name`` = Fixed name 
``default_name`` = Default name to be used if the user does not set it differently

Name is usually set for fixed objects (e.g., ``data`` or ``timestamps`` in a TimeSeries, where the quantity is 0 or 1,) whereas ``default_name`` is usually used for reusable neurodata_types where you want to allow more than one instance in the same group.

**Comment by bendichter** [comment]
The specific problem is the name argument in the `sim_meta_data`  call. `sim_meta_data` currently requires a name argument and will not run without one. The desired behavior is to run without one and throw an error if a name argument is provided.
