### ISSUE TITLE
Ensure all specs are validated

### ISSUE THREAD

**Issue by dsleiter** [hdmf-dev/hdmf#507]
## Description

Currently, there are a few edge cases where specs do not get validated, as raised in https://github.com/hdmf-dev/hdmf/pull/500. We want to ensure that all specs get correctly validated.

1. if a group includes two or more children with the same defined data type but a different name (independent of the quantity), then only the last instance will be validated. Eg. for an electrodes group that has VectorData X, Y, and Z - only Z will be validated. The validator should validate each of these children.
2. if a child link has the same data type as a child group or dataset, then the link will be validated but the group or dataset with the same data type will not be validated. The validator should validate both the link and the group or dataset.
3. if a group specifies two unnamed child groups of type A and B, where B inherits from A, then a single child of type B satisfies the spec for both B and A. The validator should require distinct children to match each spec. Both of the following cases should satisfy the spec: a) one child of type A and one of type B, or b) two children of type B.

## Steps to Reproduce

Create an hdmf object and spec which should be invalid according to one of the three points above, and see that it passes validation.

## Environment

    Python Executable: Conda or Python
    Python Version: Python 3.5, 3.6, 3.7, or 3.8
    Operating System: Windows, macOS or Linux
    HDMF Version: 2.3.0

## Checklist

- [x] Have you ensured the bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by dsleiter** [comment]
A solution for this issue should also validate correct regarding the discussion here: https://github.com/hdmf-dev/hdmf/pull/500/files#r555552469

**Comment by rly** [comment]
Thanks for writing this up, @dsleiter. Would you be able to work on this?

**Comment by dsleiter** [comment]
@rly sure! I'll get started on it this week.

**Comment by dsleiter** [comment]
@rly I ran into another question while working on this. It looks like the validator does not currently check for additional attributes, datasets, groups, or links attached to a builder that are not part of the spec.

eg. imagine a group spec for type Foo defines two child datasets: X, and Y. Validation of a group builder for Foo with three child datasets X, Y, and Z will not return any validation errors.

Is this the desired intended behavior? I wasn't able to find anything specific to this in the hdmf documentation, but I might have missed it. I did find discussion related to this in nwb-schema docs which suggests that extending data types is the intended way of adding additional elements (last paragraph of section 1.3 here: https://nwb-schema.readthedocs.io/en/latest/format_description.html#time-series-a-base-neurodata-type-for-storing-time-series-data)

**Comment by rly** [comment]
@dsleiter sorry for the delay in response.

This is related to:
https://github.com/NeurodataWithoutBorders/nwb-schema/pull/468/files
https://github.com/NeurodataWithoutBorders/pynwb/issues/1332
https://github.com/NeurodataWithoutBorders/pynwb/issues/942
https://github.com/NeurodataWithoutBorders/pynwb/pull/1178
https://github.com/hdmf-dev/hdmf/pull/288

In short, a warning should be raised on extra attributes/datasets/groups/links that are not part of the spec. 

If you want to tackle that, you could finish #288 or start your own PR to do it. As you can see from the various issues raised about it, this issue does come up and it would be very useful to add a warning on extra fields into the validator.

**Comment by t-b** [comment]
Yes this would be definitly helpful in getting finished.

**Comment by dsleiter** [comment]
Oh, great thanks! I should have checked the existing issues first.

I'd be happy to continue on #288 after this current issue. I think that the refactoring of `GroupValidator` I'm working on here will facilitate identifying superfluous objects, so I think it makes sense to complete this one first.
