### ISSUE TITLE
Support validation of ExternalResources

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf#509]
# Problem

This issue is related to the use of ontolgies. When referencing ``ExternalResources`` users often need to perform additional data validation to ensure that the terms used are valid with regard to the referenced resource/ontology. 

# Proposed Solution 

Provide a base class for implementing validators for ``ExternalResources``, something like:

```
class ExternalResourceValidator:
     @classmethod
     @docval({'name': 'external_resources', 'type': ExternalResources, 'description': ' The external resources to validate'}
     def validate(cls, **kwargs):
         ...

```

The ontology would then implement a special type of the ``ExternalResourceValidator`` class to validate the individual rows of the ``ExternalResources`` table. In the case of parametrized ontologies (see https://github.com/hdmf-dev/hdmf/issues/508) the validator would also need to look up all parameter values used and validate those as well. In addition to the ``ExternalResourceValidator`` base class, one would also likely need: 

1) A class to store validation results for external resources
2) A way to specify with the normal validator which additional ExternalResourceValidators should be run

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by mavaylon1** [comment]
This will be addressed with the incorporation of TermSet in the coming weeks ~ Matthew (5/1/23)
