### ISSUE TITLE
TypeError when validating illegally-linked typed child

### ISSUE THREAD

**Issue by dsleiter** [hdmf-dev/hdmf#514]
## Description

If a group spec includes a non-linkable child, and a group builder has a link to a child of that type, then a TypeError is raised. Expected behavior is to add an IllegalLinkError to the validation errors and return without raising an error.

## Steps to Reproduce

```python
from hdmf.build import GroupBuilder, DatasetBuilder, LinkBuilder
from hdmf.spec import GroupSpec, DatasetSpec, SpecCatalog, SpecNamespace
from hdmf.validate import ValidatorMap


def setup_validatormap():
    spec_catalog = SpecCatalog()
    typed_dataset_spec = DatasetSpec('A typed dataset', data_type_def='Foo')
    spec = GroupSpec('A test group specification with a data type',
                     data_type_def='Bar',
                     datasets=[
                         DatasetSpec('A non-linkable child dataset', data_type_inc='Foo',
                                     name='typed_nonlinkable_ds', linkable=False),
                     ])
    spec_catalog.register_spec(typed_dataset_spec, 'test.yaml')
    spec_catalog.register_spec(spec, 'test.yaml')
    namespace = SpecNamespace(
        'a test namespace', 'test_namespace', [{'source': 'test.yaml'}], version='0.1.0', catalog=spec_catalog)
    return ValidatorMap(namespace)


vmap = setup_validatormap()
link = LinkBuilder(name='typed_nonlinkable_ds',
                   builder=DatasetBuilder('foo', attributes={'data_type': 'Foo'}))
builder = GroupBuilder('my_bar', attributes={'data_type': 'Bar'}, links=[link])
result = vmap.validate(builder)
```

## Environment

    Python Executable: Conda
    Python Version: Python 3.8
    Operating System: Linux
    HDMF Version: 2.3.0

## Checklist

- [x] Have you ensured the bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by dsleiter** [comment]
I encountered this while adding tests to validate linkable groups and datasets in the process of refactoring for #507. The cause is here:
https://github.com/hdmf-dev/hdmf/blob/be7e41fec4eea78c0fe473819e0de1d9a00d1743/src/hdmf/validate/validator.py#L469-L475

When the validator encounters an illegal link, it does not redirect `child_builder` to point to the dataset/group builder (like it does when the spec is linkable), but still attempts to validate `child_builder` against the dataset/group spec.

**Comment by dsleiter** [comment]
I have a tentative fix for this already, and would be happy to make a PR, but encountered another question:

If a child dataset/group spec is non-linkable, but the child is linked via a `LinkBuilder` in the builder and leads to an `IllegalLinkError`, should the `DatasetBuilder`/`GroupBuilder` that the `LinkBuilder` points to still be validated against the spec?

I haven't created tests to verify yet, but it appears to me that the child builder will be validated in case of a typed child spec, but will not be validated in the case of an untyped child spec.

**Comment by dsleiter** [comment]
Forgot to include the error raised:
```
TypeError: DatasetValidator.validate: incorrect type for 'builder' (got 'LinkBuilder', expected 'DatasetBuilder')
```
From this line:
https://github.com/hdmf-dev/hdmf/blob/be7e41fec4eea78c0fe473819e0de1d9a00d1743/src/hdmf/validate/validator.py#L475

**Comment by rly** [comment]
@dsleiter Thanks for finding this bug and making a fix. 

> should the DatasetBuilder/GroupBuilder that the LinkBuilder points to still be validated against the spec?
I think either behavior is acceptable, but I lean toward saying the pointed-to dataset/group needs not be traversed and validated if the link is invalid. There is no way for the link to become valid except for changing the spec, so any validation errors or successes in the pointed-to dataset/group are not relevant. @oruebel what do you think?

Also worth noting that `linkable=False` has so far been rarely used.

**Comment by oruebel** [comment]
> Also worth noting that `linkable=False` has so far been rarely used

Yes, that is a feature that was carried over from NWB 1

> should the DatasetBuilder/GroupBuilder that the LinkBuilder points to still be validated against the spec?

From a validator perspective, since the link itself is invalid, I think it is technically Ok to skip validating the link. However, if the object is skipped, then the error message should indicate clearly that the linked object was not validated because of the illegal link, so that users know that the Link was skipped. 

Generally speaking, however, the linked object must have a schema, so if its easy to validate the linked object, then I think it would be best to do so for completeness. Ideally one would then have any errors found there be part of (or a sub of) the bad link error (something like what happens when Exception are raised as a result of other Exception where you then get a list of all the Exceptions that were raised as a result). Given how rare ``linkable=False`` is, however, just skipping the link should be fine for now.

**Comment by dsleiter** [comment]
Thanks for the feedback @rly and @oruebel.

Just to make sure we're on the same page, what do you think about this strategy?

1. for this issue, I will update the PR to NOT validate illegally linked objects, and also update the message for `IllegalLinkError` to clearly indicate that the linked object will not be validated
2. add a new issue to validate illegally linked objects, but nest all Errors for that object as part of the `IllegalLinkError`

If that sounds good, then I'll go ahead and update #515 and create the issue!

**Comment by oruebel** [comment]
> what do you think about this strategy?

Agreed, that sounds reasonable.

**Comment by dsleiter** [comment]
Ok, I updated the PR, and believe it is ready for review.

I also created this issue: https://github.com/hdmf-dev/hdmf/issues/516
