### ISSUE TITLE
spec boolean written as string

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#532]
In some environments, a cached spec with booleans (e.g. an attribute where required=False) is written as `required: "false"` (false as a string instead of a bool). This writes without error but causes a build error when it is read in pynwb with `load_namespaces=True`. @owoolnough came across this error and I have not yet been able to reproduce the write error.

**Comment by rly** [comment]
Do we know whether this was written with PyNWB, MatNWB, or other? What version of the schema was this?

**Comment by bendichter** [comment]
Oh it might have been MatNWB. That would explain it!
