### ISSUE TITLE
ruamel.yaml.safe_load() is deprecated

### ISSUE THREAD

**Issue by jwodder** [hdmf-dev/hdmf#547]
As of the release of ruamel.yaml 0.17.0 several hours ago, this package's use of `ruamel.yaml.safe_load()` now raises the following warning:

```
PendingDeprecationWarning:
safe_load will be removed, use

  yaml=YAML(typ='safe', pure=True)
  yaml.load(...)

instead
```

## Environment

    Python Executable: Python
    Python Version: Python 3.7, 3.8, and 3.9
    Operating System: Windows, macOS, and Linux
    HDMF Version: 2.4.0

## Checklist

- [x] Have you ensured the bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
Thanks @jwodder. We'll look into refactoring for this. It looks like there will be deprecations and breaking changes in version 1.0 of ruamel.yaml.
