### ISSUE TITLE
NWBHDF5IO fails to read on dev

### ISSUE THREAD

**Issue by CodyCBakerPhD** [hdmf-dev/hdmf#562]
## Description

This issue occurs while in the process of trying to test the current dev branch as a solution to a recurrence of [pynwb Issue #1337](https://github.com/NeurodataWithoutBorders/pynwb/issues/1337) for some different data and extension combinations we just received.

Attempting to use the dev branch (not pypi release) of hdmf won't run `io.read()` on the NWBFile. Returns this error

![image](https://user-images.githubusercontent.com/51133164/114248900-fd47ff00-9966-11eb-9f36-df55116ff2d9.png)

@rly was told to let you know
cc: @bendichter 

## Steps to Reproduce

In a fresh environment
```
git clone --recurse-submodules https://github.com/hdmf-dev/hdmf
pip install pynwb
pip uninstall hdmf
pip install -e hdmf
```
then
```
import my_extension
from pynwb import NWBHDF5IO

io = NWBHDF5IO("my_file.nwb", mode="r", load_namespaces=True)
nwbfile = io.read()
```

## Environment

The above, as of the posting of this issue, gives versions

    Python Executable: Python
    Python Version: 3.8.3
    Operating System: Windows
    HDMF Version: `dev` branch (main branch)
    PyNWB Version: 2.4.0

## Checklist

- [X] Have you ensured the bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
@CodyCBakerPhD Thanks. I'll look into this by end of day Monday. There are a few bug fixes to be merged that might resolve it.

**Comment by CodyCBakerPhD** [comment]
@rly Can confirm [PR #561](https://github.com/hdmf-dev/hdmf/pull/561) fixes this for me, thanks!
