### ISSUE TITLE
remove test formatting

### ISSUE THREAD

**Issue by ajtritt** [hdmf-dev/hdmf#578]
Whatever formatting is being used to run the tests makes it really difficult to tell which tests have passed. Can we get rid of this?

**Comment by rly** [comment]
I agree. I thought it was nice at first, but it is a burden to find the traceback. I'll undo that. 

A related but separate issue is that I would like us to use pytest to streamline test writing and add more customization. I have been using it locally and it's great. `pytest -l --pdb` is very useful in showing local variables and starting pdb on test failure/error.
