### ISSUE TITLE
Add best practices section for using ExternalResources

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#599]
## Description

`ExternalResources` provides flexibility in which resource to use and whether redundant (resource, entity) pairs should be used. We should provide a best practices / recommended usage guide.

I think it should include:
- URIs are optional, but highly recommended. If not known, an empty string may be used.
- Use an entity ID and URI from Identifiers.org. If the entity ID is not registered with Identifiers.org, you can create an account on Identifiers.org, register it yourself, and then use the newly registered entity ID and URI.
- Entity IDs should be the unique string identifying the entity in the given resource. This may or may not include a string representing the resource and a colon. Use the format provided by the resource. For example, Identifiers.org uses the ID `ncbigene:22353` but the NCBI Gene uses the ID `22353` for the same term. 

- TBD whether this is recommended, but adding it here for discussion: You may add redundant / duplicated (resource, entity) pairs. This may be useful in reducing the dependency on a single resolver service such as Identifiers.org in case it goes down. For example, you may link the (container, field) `Subject.species` and key `Homo sapiens` with both the (resource, entity ID) pair (Identifiers.org, taxonomy:9606) and with the (resource, entity ID) pair that the Identifiers.org URI points to, (NCBI Taxonomy, NCBI:txid9606).

@oruebel @rightbower Any other best practices to add or discuss?

**Comment by oruebel** [comment]
>     * URIs are optional,

Shouldn't the URI be required at the very least for the resource? Without a URI the link to the external resource is broken.

>     * Use an entity ID and URI from Identifiers.org.

We should indicate what the advantages of using Identifiers.org are.

>     * You may add redundant / duplicated (resource, entity) pairs.

I would make this a recommendation only if the generators of the data themselves are actually using multiple resources. I think populating the file with backup links ultimatley leads to confusion which resources the data generators actually used, in particular in case there are discrepancies or inconcistencies between the different resources used.

**Comment by mavaylon1** [comment]
URIs are not optional. They are required.

**Comment by mavaylon1** [comment]
Unless someone put's in an empty string. They just can't be left as None.

**Comment by mavaylon1** [comment]
I'll include this Best Practice in the tutorial pull request.
