### ISSUE TITLE
Support append of ExternalResources

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf#635]
When adding data to files or further annotating existing data, users will need to able to append rows to the ExternalResources tables. In order to be able to do this, the ExternalResources datasets will need to be chunked and saved with a maxschape of (None,). In order to achieve this, the different compound datasets that make up ExternalResources will likely need to be wrapped in DataIO (or H5DataIO objects, depending on the backend).

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by oruebel** [comment]
CC @ajtritt @rly

**Comment by mavaylon1** [comment]
@oruebel currently we don’t allow appending individual tables for external resources. Since this was made back in June, is this still relevant?

**Comment by oruebel** [comment]
@mavaylon1, yes this is still relevant. The issue is not about appending individual tables. The issue is the following.

1. User creates a file and populates the ExternalResources
2. User writes the file to disk
3. User reads the file (and possibly modifies the file , e.g., to add a new data container) 
4. User needs to modify ExternalResources, e.g., to add an ontology to either an existing or a new field they added

After writing the data to disk, the arrays you are dealing with in the ExternalResources class are no longer numpy arrays, but HDF5 datasets. In HDF5, however, we can only grow datasets if they were created not as fix-sized datasets, but as chunked datasets with an unlimited dimension along the axis we want to grow. In HDMF/PyNWB we can do this by wrapping the dataset we write via the HDF5IO class. See here for a tutorial on this https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/h5dataio.html#sphx-glr-tutorials-advanced-io-h5dataio-py For external resources chunking should be used by default as it is likely that users will need to add to the ExternalResources after the file has been written to disk. I believe DynamicTable supports this already, maybe @rly can point you to the code that shows how to do this.

@mavaylon1 as a test, I would suggest to try the following:

1. Create a file with ExternalResource with some entries
2. Read the file in append mode 'a' 
3. Call add_ref for the ExternalResources to add a new row 

Currently, I believe this should fail, because the HDF5 datasets for ExternalResources cannot be expanded.

**Comment by mavaylon1** [comment]
Closing due to ER no longer being written with NWBFile and will be written as a separate file.
