### ISSUE TITLE
Enhance support for modular storage of large datasets

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf#644]
For very large files it will be useful to separate very large data arrays into separate files to: 1) enable update of metadata without affecting the bulk data, 2) simplify shipping of data. 

**Current:** Users can:
1. write datasets on their own using h5py and then link to the data from HDMF containers.
2. write whole containers to separate HDF5 files with HDMF and then link to the whole container or parts of that container later on.

**Problem:** The current logic requires users to control the process on a per-dataset basis and placing individual datasets into external files is only possible when using h5py directly. It would be useful to provide some additional functionality to allow users to do this directly from HDMF

**Approaches**
1) Enhance H5DataIO to support specification of target file (and path) for storage and update HDF5IO accordingly. This would allow users to specify individual datasets that should be written to separate HDF5 files. 
2) To avoid having to wrap datasets individually and allow for more standardized formatting, it would be useful to enhance HDF5IO to provide an automated logic to write large datasets (i.e., bulk data) to separate files. E.g., a user could set a threshold (e.g,. 100MB) to then write all datasets larger than the threshold to an external file. 
3) Support creation of VirtualDatasets to support breaking down datasets itself into further files. See also https://github.com/hdmf-dev/hdmf/issues/135

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [-] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by mavaylon1** [comment]
@oruebel 
To address your points:
1) Couldn't this be done with a side care of metadata? @rly
2) I'm not sure this actually simplifies data shipping since it results in multiple files.

**Comment by oruebel** [comment]
I think we can close this issue for now. I think hdmf-zarr and lindi may be more appropriate to address the issue. We can reopen if necessary.
