### ISSUE TITLE
Add tutorial for DynamicTableRegion and Linked Tables

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf#648]
It would be useful to have a tutorial dedicated to ``DynamicTableRegion`` and how to use to: 1) link to metadata stored in tables, and 2) link between tables (similar to a foreign key in a database). This tutorial should cover:

- Creating DynamicTableRegions
- Using DynamicTableRegion as column in a DynamicTable
- Interacting with tables that contain DynamicTableRegions
- Constructing table  hierarchies and the convenience functions available in ``hdmf.common.hierarichaltable``

This issue has been identified as part of PR https://github.com/hdmf-dev/hdmf/pull/645 and the functionality is being used in PyNWB as part of the ICEphys metadata tables defined in https://github.com/NeurodataWithoutBorders/pynwb/pull/1383

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by mavaylon1** [comment]
This exists in the tutorials. https://hdmf.readthedocs.io/en/dev/tutorials/plot_dynamictable_howto.html#sphx-glr-tutorials-plot-dynamictable-howto-py
