### ISSUE TITLE
Overwriting file with object already in file creates broken link and failure to write

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#65]
**Bug**

Pseudocode:
- create container C1
- add object O to container C1
- write container C1 to file F
- create container C2
- add same object O to container C2
- write container C2 to file F

This results in a broken link to object O, and file F no longer has object O.

This example uses pynwb but it also applies to custom containers. 

```python
from datetime import datetime
from dateutil.tz import tzlocal
from pynwb import NWBFile, TimeSeries, NWBHDF5IO, get_manager
import numpy as np

start_time = datetime(2017, 4, 3, 11, tzinfo=tzlocal())

nwbfile = NWBFile(session_description='demonstrate NWBFile basics',  # required
                  identifier='NWB123',  # required
                  session_start_time=start_time)  # required

data = list(range(100, 200, 10))
timestamps = list(range(10))
test_ts = TimeSeries(name='test_timeseries1', data=data, unit='m', timestamps=timestamps)
nwbfile.add_acquisition(test_ts)

with NWBHDF5IO('example_file_path.nwb', manager=get_manager(), mode='w') as io:
    io.write(nwbfile)

# do it again
nwbfile = NWBFile(session_description='demonstrate NWBFile basics',  # required
                  identifier='NWB123',  # required
                  session_start_time=start_time)  # required

# add object that already exists and was added to the file
nwbfile.add_acquisition(test_ts)

# add new object
test_ts2 = TimeSeries(name='test_timeseries2', data=data, unit='m', timestamps=timestamps)
nwbfile.add_acquisition(test_ts2)

with NWBHDF5IO('example_file_path.nwb', manager=get_manager(), mode='w') as io:
    io.write(nwbfile)  # broken link warnings

with NWBHDF5IO('example_file_path.nwb', manager=get_manager(), mode='r') as io:
    read_file = io.read()
    print(read_file)  # missing test_timeseries1

```

**Environment**

Please describe your environment according to the following bullet points.

    Python Executable: Conda
    Python Version: Python 3.7
    Operating System: Windows
    HDMF Version: latest dev

**Comment by rly** [comment]
Finally got around to investigating this issue. The core issue is that under this procedure:
1. create container C1
2. add object O to container C1
3. write container C1 to file F
4. create container C2
5. add same object O to container C2
6. write container C2 to file F

On step 5, there should have been an error thrown that the `parent` of O cannot be reassigned. Changing the code so that this constraint is enforced has implications for how user code is written. Objects cannot be added to multiple containers. This makes sense, but just to confirm, this is intended behavior, right? @ajtritt

**Comment by rly** [comment]
If this is right, how are internal hard/soft links created?

This test would fail:
```python
class TestLinkResolution(unittest.TestCase):

    def test_link_resolve(self):
        foo1 = Foo('foo1', [0, 1, 2, 3, 4], "I am foo1", 17, 3.14)
        bucket1 = FooBucket('test_bucket1', [foo1])
        foo2 = Foo('foo2', [5, 6, 7, 8, 9], "I am foo2", 34, 6.28)
        bucket2 = FooBucket('test_bucket2', [foo1, foo2])
        foofile = FooFile([bucket1, bucket2])

        with HDF5IO(self.path, 'w', manager=_get_manager()) as io:
            io.write(foofile)

        with HDF5IO(self.path, 'r', manager=_get_manager()) as io:
            foofile_read = io.read()

        b = foofile_read.buckets
        b1, b2 = (b[0], b[1]) if b[0].name == 'test_bucket1' else (b[1], b[0])
        f = b2.foos
        f1, f2 = (f[0], f[1]) if f[0].name == 'foo1' else (f[1], f[0])
        self.assertIs(b1.foos[0], f1)
```

**Comment by oruebel** [comment]
> If this is right, how are internal soft links created?

The creation of internal soft-links and external links should essentially be the same, the only difference being that for soft-links the object is re-added to the same file and for external it is re-added to a different file.

**Comment by rly** [comment]
The example situation is a bit contrived. The correct way to handle the above situation, given that `test_ts` has already been written and overwriting the file where `test_ts` lives will break any links to `test_ts` in the new file, is to perform a deepcopy of `test_ts`. i.e. in the original example, replace the addition of `test_ts` to the second `NWBFile` instance with the following:

```python
from copy import deepcopy

# add object that already exists and was added to the file
nwbfile.add_acquisition(deepcopy(test_ts))
```

This requires a `Container.__deepcopy__` function which:
1) resets the `parent` to None
2) resets the `container_source` to None
3) sets a new `object_id`
4) sets `modified` to True
5) sets all children's `parent` to itself

**Comment by rly** [comment]
Writing an in-memory object that was previously written to a file is not recommended. This has not come up in practice except from me. Closing unless it is a priority.
