### ISSUE TITLE
Test failure when building on Fedora rawhide (36): AssertionError: "^can't\ set\ attribute$" does not match "can't set attribute 'key_attr'"

### ISSUE THREAD

**Issue by sanjayankur31** [hdmf-dev/hdmf#663]
## Description

When building hdmf 3.1.1 on Fedora, one test fails with:

```
======================================================================
FAIL: test_set_key_attr (utils_test.test_labelleddict.TestLabelledDict)
Test that the key attribute cannot be set after initialization.
----------------------------------------------------------------------
AttributeError: can't set attribute 'key_attr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/hdmf-3.1.1/tests/unit/utils_test/test_labelleddict.py", line 36, in test_set_key_attr
    with self.assertRaisesWith(AttributeError, "can't set attribute"):
AssertionError: "^can't\ set\ attribute$" does not match "can't set attribute 'key_attr'"

----------------------------------------------------------------------
Ran 1220 tests in 7.455s

FAILED (failures=1, skipped=8, expected failures=1)
======================================================================
2021-08-16 18:55:36,332 - INFO - Ran 1220 tests - FAILED (failures=1)

```
The final regex isn't matching: should it be using `assertRaisesWith` here, which I see does an exact match?

## Steps to Reproduce

N/A

## Environment

    Python Executable: python
    Python Version: Python 3.7, 3.8, or 3.9: python3.10
    Operating System: Windows, macOS or Linux: Fedora Linux
    HDMF Version: 3.1.1

## Checklist

- [x] Have you ensured the bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [-] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [-] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

Build logs attached:

[hdmf-buildlog.txt](https://github.com/hdmf-dev/hdmf/files/6994432/hdmf-buildlog.txt)
[hdmf-rootlog.txt](https://github.com/hdmf-dev/hdmf/files/6994433/hdmf-rootlog.txt)

**Comment by rly** [comment]
Python 3.10 must have changed the error message for an `AttributeError` when the user tries to set a property that cannot be set. We need not check for an exact match of this error message.

**Comment by sanjayankur31** [comment]
Thanks, I'm carrying the patch downstream for the time being too.
