### ISSUE TITLE
Downstream tests fail with `KeyError: "'core' not a namespace"`

### ISSUE THREAD

**Issue by TheChymera** [hdmf-dev/hdmf#671]
Downstream test collection fails, with a traceback which leads to hdmf: https://ppb.chymera.eu/cde8fd
The hdmf installation passes the full test suite, so we don't know whether we might be using your package improperly here?

## Environment

    Python Executable: Python
    Python Version: 3.9
    Operating System: Linux
    HDMF Version: 3.1.1

**Comment by oruebel** [comment]
I assume this is in combination with PyNWB.  ``core``  is the name of the main NWB namespace. Usually I have seen this error in the past when cloning PyNWB from git directly without including the `` --recurse-submodules`` option. PyNWB includes the ``nwb-schema`` git repo as a submodule with the YAML schema files for NWB. When the submodule is not being checked out, then the files are missing and the core namespace cannot be loaded. I.e., when cloning PyNWB from git you should use: 

``git clone --recurse-submodules git@github.com:NeurodataWithoutBorders/pynwb.git``

**Comment by TheChymera** [comment]
@oruebel I thought this might be the issue. I am using the package release which (allegedly?) includes everything.

https://github.com/NeurodataWithoutBorders/pynwb/releases/download/2.0.0/pynwb-2.0.0.tar.gz

**Not** the github-autogenerated source archive https://github.com/NeurodataWithoutBorders/pynwb/archive/refs/tags/2.0.0.tar.gz

Is this still not sufficient? If so is there any release archive which includes these resources, or would I need to manage `nwb-schema` as a separate package and lock the version dependency?

**Comment by oruebel** [comment]
Looking at the tar.gz file it looks like it does indeed include the schema. I have to admit, I usually install from pip/conda when I need a production environment and I install directly from git when I need a development environment, i.e., I usually never install from the tar.gz file. If installing from pip, conda, or git is an option for you  then I would recommend to try those paths instead, at least while we are chasing down this issue. Could you provide a listing of how your are installing the software and setting up your environment so that I can try an reproduce the issue on my end. We may ultimately need to pull in @rly into this discussion, since he manged the release for PyNWB and HDMF. However, I think @rly may not be able to respond until next week, and I would like to try and at least trace down the source for this issue a bit more.

**Comment by TheChymera** [comment]
@oruebel ok, so I tried to install it from the pypi sources as well, and I get the same issue with the downstream test suite. I also checked, and both the github and the pypi sources install the same files (full list [here](https://ppb.chymera.eu/bcc55e)).

And [this is the full build log, including tests](https://ppb.chymera.eu/89c63b).

**Comment by oruebel** [comment]
Just for clarification, did you use ``pip install -U pynwb`` or did you download the [tar](https://files.pythonhosted.org/packages/10/06/7ee400e4613ad8cbe193f873137c30869575a18e68677bbd87ea1486806f/hdmf-3.1.1.tar.gz) file and install manually from that?

**Comment by TheChymera** [comment]
@oruebel manual download and install. PIP won't cut it as it doesn't integrate well with the rest of the dependency management system.

**Comment by oruebel** [comment]
Thanks for the clarification. I'll try to work on this later today, but can't make any promises right now. We may not be able to get to it this week, but I'll make sure to bring it up with the team in our sync-up on Monday to make sure we find cycles for this issue.

**Comment by TheChymera** [comment]
@oruebel thank you for looking into it :)

Some other thing I just ran into, which (hopefully) might help shed light on the issue, is that another downstream package, PyNWB, *also* produces these errors, but *only* if it is run as user:
1. PyNWB tests ran as root inside the installation sandbox: https://ppb.chymera.eu/069f03.log (using the GitHub “full” resease archive).
2. PyNWB tests ran as user: https://ppb.chymera.eu/e2dfcc (inside the git repo, after having checked out the corresponding release commit).

Just to re-state (hopefully this extra bit of info doesn't make this more confusing), the dandi-cli errors I initially reported happen *both* when running the tests from full GitHub release archive and from the git repo (i.e. analogous to both 1. and 2. as described above).

**Comment by oruebel** [comment]
Thanks for the additional details.

> but _only_ if it is run as user:

If the tests run as root but not as users, then my guess is that there might be some funky permission issue happening, e.g., where root has read access to the core schema files but user does not. Can you double check that user has proper read permissions on all files. Maybe things where installed as root and the permissions didn't get updated for some reason on some files.

>  is that another downstream package, PyNWB, _also_ produces these errors

As far as I can tell, the original error was also triggered by PyNWB. In general, HDMF does not include the core namespace, so any failures related to the core namespace should involve PyNWB.

**Comment by rly** [comment]
Hi @TheChymera , how are you installing PyNWB (commands and download sources) and how are you running PyNWB tests as a user (item 2 in your last comment)?

To be clear here -- the `"'core' not a namespace" test is a test failure from PyNWB, not HDMF. It is the result of the nwb-schema files not being properly loaded. 

For my and future reference:
These schema files are normally installed as `package_data` in `setup.py`:
https://github.com/NeurodataWithoutBorders/pynwb/blob/e484bfd0208a9777bc6c45e44a4cfa3a900cffe3/setup.py#L46 

and the paths to these files are determined in PyNWB using the `resource_filename` function from the `pkg_resources` package:
https://github.com/NeurodataWithoutBorders/pynwb/blob/e484bfd0208a9777bc6c45e44a4cfa3a900cffe3/src/pynwb/__init__.py#L28

**Comment by TheChymera** [comment]
@rly ok, very strange, I just wiped the dependency graph clean and started over, and the issue went away. No idea what was causing it :( But good news I guess :) I'll open this back up if the issue comes up again.
