### ISSUE TITLE
jsonschema is limited to <4 which seems unnecessary.

### ISSUE THREAD

**Issue by TheChymera** [hdmf-dev/hdmf#674]
## Description

The test suite passes (`1210 passed, 9 skipped, 1 xfailed, 41 warnings in 41.19s`) with the exact same numbers whether I have jsonschema `3.2.0` or the more recent `4.1.0`.

Is this safe to remove?

## Steps to Reproduce

```
pytest -vv
```

## Environment

    Python Executable: Python
    Python Version: 3.9
    Operating System: Linux
    HDMF Version: 3.1.1

**Comment by oruebel** [comment]
I think upgrading the jsonschema version should probably be save. Feel free to submit a PR for this.
