### ISSUE TITLE
Test test_set_key_attr fails with Python3.10

### ISSUE THREAD

**Issue by tillea** [hdmf-dev/hdmf#687]
## Description

Debian is switching from Python3.9 to Python3.10.  While all tests are passing with Python3.9 there is a single test failure with Python3.10:

    test_set_key_attr (tests.unit.utils_test.test_labelleddict.TestLabelledDict)
    Test that the key attribute cannot be set after initialization. ... FAIL
    ...
    ======================================================================
    FAIL: test_set_key_attr (tests.unit.utils_test.test_labelleddict.TestLabelledDict)
    Test that the key attribute cannot be set after initialization.
    ----------------------------------------------------------------------
    AttributeError: can't set attribute 'key_attr'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/build/hdmf-3.1.1/.pybuild/cpython3_3.10_hdmf/build/tests/unit/utils_test/test_labelleddict.py", line 36, in test_set_key_attr
        with self.assertRaisesWith(AttributeError, "can't set attribute"):
    AssertionError: "^can't\ set\ attribute$" does not match "can't set attribute 'key_attr'"

    ----------------------------------------------------------------------

## Steps to Reproduce

You should be able to reproduce the issue when using Python3.10.1

## Environment

    Python Executable: Python
    Python Version: Python 3.10
    Operating System: Debian Linux attempt to build the package in minimum chroot
    HDMF Version: 3.1.1

## Checklist

- [x] Have you ensured the bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment]
Thanks @tillea! It looks like the code is performing as expected in Python 3.10, and the only reason this test is failing is that the error message is slightly different. We should be able to fix this easily by changing this from `self.assertRaisesWith` to `self.assertRaises` and remove the check for the error message.

**Comment by bendichter** [comment]
@tillea this would be a good first issue if you are so inclined ;-)

**Comment by tillea** [comment]
Am Wed, Dec 22, 2021 at 05:35:43AM -0800 schrieb Ben Dichter:
> Thanks @tillea! It looks like the code is performing as expected in Python 3.10, and the only reason this test is failing is that the error message is slightly different. We should be able to fix this easily by changing this from `self.assertRaisesWith` to `self.assertRaises` and remove the check for the error message.
Yes, I think its just the string comparison - but I've thought it would be worth reporting. ;-)

**Comment by rly** [comment]
It turns out that this test failure has already been fixed in the dev branch. To prevent similar test failures in future versions of Python, I removed testing against the exact text of a base/native Python error messages in #689.
