### ISSUE TITLE
Migrate nwb-docutils to NWB agnostic location

### ISSUE THREAD

**Issue by ajtritt** [hdmf-dev/hdmf#7]
Migrate nwb-docutils into hdmf-dev organization and add to documentation to HDMF docs.

Originally, the HDMF documentation discussed using nwb-docutils for building schema documentation. This was removed [here](8dbbb2466d1e88c95af3717c20ec3d166a05b678)

Currently, [nwb-docutils](https://github.com/NeurodataWithoutBorders/nwb-docutils) contains scripts for building schema documentation, but needs to be generalized for other standards.

**Comment by rly** [comment]
I believe this is now done: https://github.com/hdmf-dev/hdmf-docutils
