### ISSUE TITLE
Update CircleCI images

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#703]
CircleCI reports that we are using legacy images.

> Legacy images with the prefix "circleci/" will be [deprecated](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) on December 31, 2021. For faster builds, upgrade your projects with [next-generation convenience images](https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/).

- https://circleci.com/docs/2.0/circleci-images/

We should update the CircleCI images.

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment]
we've been having a lot of success using just GitHub actions for our repos. Do you think you might want to switch over? @CodyCBakerPhD has gotten really good at setting up CI

**Comment by rly** [comment]
CircleCI has stopped running for PRs as of 16 days ago, but strangely still runs for nightly builds - even though they are all in the same file. I did not touch the file 16 days ago but I may have accidentally deleted the CircleCI webhook when trying to get readthedocs to work. In any case, I think it is time to migrate more fully to GitHub Actions. The CI for a PR might take a little longer (due to limited concurrent jobs), but it will be one fewer external service to manage and maintain integration with.
