### ISSUE TITLE
is there the equivalent of netCDF CDL for HDMF

### ISSUE THREAD

**Issue by cmungall** [hdmf-dev/hdmf#708]
caveat: I am not an expert on either netCDF or HDMF

netCDF provides CDL which is an (albeit odd) compromise between machine and human readability. It makes it very easy to grok the contents of a file without having to use specialized code to crack open a binary format.

Maybe I am not a typical HDMF user but I would find it very useful to have an analog, to being to quickly explore the contents of a HDMF file, to see what kinds of variables are being measured (and my own interest, are these mapped to standard vocabularies)

**Comment by oruebel** [comment]
I don't know the CDL tool in much detail, so I'm not sure if this covers what you are looking for, but let me provide a few options to see whether one of these covers what you need:

- The ``Container`` class has a default ``__repr__`` method defined which should print the contents. I.e., in Python you can just call print(mycontainer) for this
- HDMF files are stored in HDF5 so standard HDF5 tools work as well

    - ``h5ls`` (with the `` -r -v`` options) provides an oveview  of all objects in a file (see https://portal.hdfgroup.org/display/HDF5/h5ls)
    - ``h5dump`` is useful if you want to dive a bit deeper in the actual data instead of just the structure of the file (see https://portal.hdfgroup.org/display/HDF5/h5dump)
    - ``HDFView`` is also useful if you want to browse contents (see https://portal.hdfgroup.org/display/HDFVIEW/HDFView)
    - For a full list of HDF5 command line tools see: https://portal.hdfgroup.org/display/HDF5/HDF5+Command-line+Tools

**Comment by cmungall** [comment]
This is just what I wanted, thanks!

**Comment by bendichter** [comment]
If you are in Python, this might be helpful: https://gist.github.com/bendichter/8f605d6d3e5a7b11a00255278aa2d5f9
