### ISSUE TITLE
[Feature]: autobuild readthedocs

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#713]
### What would you like to see added to HDMF?

@rly, could you set up hdmf like you did with pynwb to automatically build the docs for a PR and provide a link in the PR tests?

### What solution would you like?

@rly, could you set up hdmf like you did with pynwb to automatically build the docs for a PR and provide a link in the PR tests?

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by rly** [comment]
Great idea. I've set this up now. I will do the same on the other repos. Thanks!
