### ISSUE TITLE
[Feature]: add more traceback or module/package info for FutureWarning

### ISSUE THREAD

**Issue by yarikoptic** [hdmf-dev/hdmf#745]
### What would you like to see added to HDMF?

traceback on what lead to FutureWarning?

in https://github.com/dandi/helpdesk/discussions/77  I saw

```
> dandi validate /allen/programs/celltypes/production/humancelltypes/prod218/Ephys_Roi_Result_636991746/EPHYS_ATTACH_METADATA_QUEUE_1187479409/636991746_ephys.nwb
/home/nicholas.mei/miniconda3/envs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py:577: FutureWarning: DynamicTable.__init__: Using positional arguments for this method is discouraged and will be deprecated in a future major release. Please use keyword arguments to ensure future compatibility.
  warnings.warn(msg, FutureWarning)```
```
so I thought that `hdmf/utils.py:577` is the place of the problem! 

### What solution would you like?

 I wonder if it would be nice to include few levels of traceback or module name for that class to point to specific module which cases that warning?

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by rly** [comment]
Would adding `stacklevel=2` help? See #1027. The output for a similar example would be:
```
  /Users/rly/Documents/NWB/hdmf/test_warnings.py:3: FutureWarning: DynamicTable.__init__: Using positional arguments for this method is discouraged and will be deprecated in a future major release. Please use keyword arguments to ensure future compatibility.
    DynamicTable("test", "test")
```
which identifies the file and line number that calls `DynamicTable.__init__` (`test_warnings.py:3`) as well as the contents of that line (`DynamicTable("test", "test")`).

Beyond that, I think it would be better to run `python -Werror my_code.py` to get the full stack trace of the warning.
