### ISSUE TITLE
[Bug]: Change behavior of call_docval_func

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#748]
### What happened?

Any code that uses `call_docval_func` on a Container's `__init__` class often results in warnings that using positional arguments will be deprecated soon. This is beavuse `call_docval_func` takes in a function and keyword arguments to pass to the function, splits the arguments into positional arguments and keyword arguments based on whether the docval on the function says that the arguments is required or has a default value, and then calls the function, passing positional and keyword arguments. 

I see no reason to take keyword arguments being passed to a function and remove the keyword before calling the function. 

### Steps to Reproduce

```shell
n/a
```

### Traceback

```shell
n/a
```

### Operating System

Windows

### Python Executable

Python

### Python Version

3.9

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by oruebel** [comment]
> I see no reason to take keyword arguments being passed to a function and remove the keyword before calling the function.

Agreed
