### ISSUE TITLE
EnumData gives a warning

### ISSUE THREAD

**Issue by cmungall** [hdmf-dev/hdmf#755]
This section
https://hdmf.readthedocs.io/en/stable/tutorials/plot_dynamictable_howto.html#enumerated-categorical-data

has guidelines on EnumData, but the output in the docs says:

```
/home/docs/checkouts/readthedocs.org/user_builds/hdmf/checkouts/stable/src/hdmf/container.py:187: UserWarning: EnumData is experimental -- it may be removed in the future and is not guaranteed to maintain backward compatibility
  warn(_exp_warn_msg(cls))
```

I also get this with the latest version from PyPI

**Comment by rly** [comment]
`EnumData` is currently experimental. Either we should update the tutorial to clearly state that it is experimental and subject to change, or we can migrate it out of experimental and into the official HDMF common types. There are some open issues on `EnumData` that I think make it not ready for official release, e.g., #593, #594, #595, so I am in favor of updating the tutorial.
