### ISSUE TITLE
Prepare deprecations for HDMF 4.0

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#766]
### What would you like to see added to HDMF?

Code is marked throughout HDMF as deprecated or planned for deprecation, but those deprecations have not actually happened. These should be removed because the code is outdated or untested and it adds a cost to maintain.

1. `hdmf.get_region_slicer`
2. `Container.add_child`
3. `HDF5IO.copy_file`
4. `hdmf/build/map.py`

These functions are marked as deprecated but are used by a number of NWB extensions and older versions of PyNWB, so should be maintained for some time:
1. `hdmf.utils.fmt_docval_args`
2. `hdmf.utils.call_docval_func`

Code coverage will be increased by removing deprecated code. There are also some code that is unused and untested, such as `monitor.py`, `array.py`, `region.py`, and parts of `query.py`. 
See https://app.codecov.io/gh/hdmf-dev/hdmf/tree/dev/src/hdmf

### What solution would you like?

Removed the deprecated code.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by mavaylon1** [comment]
@rly I think we should check some extensions for `call_docval_func`.

**Comment by rly** [comment]
Fixed by #1198 and #1212 and #1221

`HDF5IO.copy_file` is kept but we can target its removal in HDMF 5.0.
