### ISSUE TITLE
[Feature]: Publish sources to Zenodo on release

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#774]
### What would you like to see added to HDMF?

This provides a secondary path to the source code outside of GitHub with unique DOIs assigned, e.g., https://zenodo.org/record/7199958#.Y03L7-zMI0Q

### What solution would you like?

Add GitHub action on release to publish to zenodo

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by oruebel** [comment]
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Comment by rly** [comment]
This is done. https://zenodo.org/records/10524933
