### ISSUE TITLE
[Bug]: `default_value` for datasets is not supported

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#792]
### What happened?

See https://github.com/NeurodataWithoutBorders/helpdesk/discussions/39

A quick ctrl-f shows that `default_value` is used only in a handful of places for data I/O (as opposed to spec I/O):
- `ObjectMapper.__add_attributes` but not `__add_datasets`
- `CustomClassGenerator.process_field_spec` which sets up docval args for the auto-generated `__init__`
- `MCIClassGenerator.process_field_spec` which sets up docval args for the auto-generated `__init__`

The schema language suggests this should be supported: https://hdmf-schema-language.readthedocs.io/en/latest/description.html#value-and-default-value

But I don't think `default_value` is used in any dataset spec that we are aware of. 
@lawrence-mbf does MatNWB support `default_value` for datasets specs?

We can either add support in the API or remove it from the language. It's not immediately clear to me anyway how `default_value` (and `value`) would be defined for anything that is not a scalar. I do not think the APIs support non-scalar values for these when defined on attributes.

### Steps to Reproduce

```shell
n/a
```

### Traceback

```shell
n/a
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.10

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by lawrence-mbf** [comment]
> does MatNWB support default_value for datasets specs?

@rly No, default values are only supported for Attributes currently.

**Comment by rly** [comment]
As of hdmf-schema-language 3.0.0, this will no longer be allowed as part of the HDMF specification language.
