### ISSUE TITLE
[Bug]: Handling of attributes with fixed value in get_class

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf#798]
### What happened?

https://github.com/NeurodataWithoutBorders/pynwb/issues/1599 describes that attributes with a fixed value are treated in ``get_class`` as having a default value of ``None`` in the constructor and then the actual fixed value is only set once the data is written. Attributes with fixed values should ideally: 1) not appear in the constructor (as they cannot be set), and b) appear as fixed-valued properties of the class (or instance) with the correct value, so that the value is visible in the Container object before write (and not just after write). 

### Steps to Reproduce

```shell
See https://github.com/NeurodataWithoutBorders/pynwb/issues/1599#issuecomment-1320271701
```

### Traceback

```shell
See https://github.com/NeurodataWithoutBorders/pynwb/issues/1599#issuecomment-1320271701
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.9

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by rly** [comment]
I'll take a look.
