### ISSUE TITLE
Add hdmf-zarr tests to HDMF test suite

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf#809]
Once hdmf-zarr is releases I think it would be useful to also add a (non-required) workflow to HDMF to have the hdmf-zarr test suite run as part of regular PRs. I don't think this should add much in term of total runtime so hopefully this will be fine. 

Alternatively (or in addition) we could also add a nightly workflow on hdmf-zarr to check each night that the library works correctly with the latest release of HDMF.

**Comment by oruebel** [comment]
This issue is not essential for the initial release but will be important to ensure that hdmf-zarr continues to function as new version of HDMF are being released.

**Comment by rly** [comment]
Great idea. I think we should add these to both on-PR and nightly tests.
