### ISSUE TITLE
[Bug]: ExternalResources children lost on read/write on roundtrip tests

### ISSUE THREAD

**Issue by mavaylon1** [hdmf-dev/hdmf#857]
### What happened?

Upon the roundtrip tests, reading and writing ExternalResources to .h5 file loses the child/parent hierarchy between ExternalResources (the parent) and the individual tables (the children)

### Steps to Reproduce

```shell
Run the roundtrip tests and see that the values are kept; however, if you check the children on read, they are lost.
```

### Traceback

```shell
N/A
```

### Operating System

macOS

### Python Executable

Python

### Python Version

3.10

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by rly** [comment]
I labeled this as high priority because it suggests a deeper issue in the codebase.
