### ISSUE TITLE
[Feature]: Create a warning if linked objects are not already present in an NWBfile.

### ISSUE THREAD

**Issue by mavaylon1** [hdmf-dev/hdmf#885]
### What would you like to see added to HDMF?

Create a warning if linked objects are not already present in an NWBfile.

### What solution would you like?

Create a warning if linked objects are not already present in an NWBfile.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by mavaylon1** [comment]
To clarify this some more, is this issue regarding the idea that if I have an object that has a DynamicTableRegion, such as electrodes for ElectrodeSeries, then we want a warning that the electrode table has not been added to the NWBFile when the series is added. In discussion this was said to be an hdmf issue. 

At first, my initial idea would be:
1. When an object has its parent set (when the ElectrodeSeries is added to the file), a check will run on the object's children (electrodes is a child). The child will have its type checked and if it is a DynamicTableRegion then it will call "table" and check the table's parents. If it has not been set then the warning is raised. 

Thoughts? @rly @oruebel

**Comment by rly** [comment]
Fixed by #891
