### ISSUE TITLE
[Bug]: HDMF is not reporting correct version in conda.

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#889]
### What happened?

HDMF not reporting correct version in conda.

This is evident in the pynwb-feedstock builds:
https://github.com/conda-forge/pynwb-feedstock/pull/51
```
pynwb 2.3.2 has requirement hdmf>=3.5.4, but you have hdmf 0.0.0.
```

See also:
https://github.com/conda-forge/hdmf-feedstock/issues/68

This seems to have to do with our recent transition from versioneer to setuptools_scm. One potential solution is to use:
```
[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
# this file is created/updated when the package is installed and used in
# src/hdmf/__init__.py to set `hdmf.__version__`
version-file = "src/hdmf/_version.py"
```
instead in `pyproject.toml`

### Steps to Reproduce

```shell
see above
```

### Traceback

```shell
see above
```

### Operating System

Linux

### Python Executable

Conda

### Python Version

3.11

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by pgunn** [comment]
I was the one who reported the feedstock issue, and the issue seems to be solved in the most recent conda package. Thanks for fixing this. Much appreciated!
