### ISSUE TITLE
[Feature]: Add tests for Python 3.12

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#904]
### What would you like to see added to HDMF?

Python 3.12 will be released on [Oct 2, 2023](https://peps.python.org/pep-0693/).

We should proactively test for compatibility with Python 3.12.

### What solution would you like?

1. Add py312 environments to `tox.ini`
2. Update GitHub Actions workflows to test on python version "3.12-dev"

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by mavaylon1** [comment]
@rly lets do this together in October
