### ISSUE TITLE
[Bug]: Import error in dev mode

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#905]
### What happened?

Error introduced by https://github.com/hdmf-dev/hdmf/pull/890

When using hdmf in an editable environment, `import hdmf` causes an import error

### Steps to Reproduce

```shell
import hdmf
```

### Traceback

```shell
NameError                                 Traceback (most recent call last)
Cell In [2], line 1
----> 1 import hdmf

File ~/dev/hdmf/src/hdmf/__init__.py:53
     34     pass
     37 from ._due import BibTeX, due  # noqa: E402
     39 due.cite(
     40     BibTeX("""
     41 @INPROCEEDINGS{9005648,
     42   author={A. J. {Tritt} and O. {Rübel} and B. {Dichter} and R. {Ly} and D. {Kang} and E. F. {Chang} and L. M. {Frank} and K. {Bouchard}},
     43   booktitle={2019 IEEE International Conference on Big Data (Big Data)},
     44   title={HDMF: Hierarchical Data Modeling Framework for Modern Science Data Standards},
     45   year={2019},
     46   volume={},
     47   number={},
     48   pages={165-179},
     49   doi={10.1109/BigData47090.2019.9005648}}
     50 """),  # noqa: E501
     51     description="HDMF: Hierarchical Data Modeling Framework for Modern Science Data Standards",
     52     path="hdmf/",
---> 53     version=__version__,
     54     cite_module=True,
     55 )
     56 del due, BibTeX

NameError: name '__version__' is not defined
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.9

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by rly** [comment]
I can't seem to reproduce this error and would like to understand why it's happening. Could you please try this:
```bash
conda create --name test python=3.9 --yes
conda activate test
cd hdmf
git pull
pip install -e .
python -c "import hdmf"
```
And report the output here? Specifically, what is the version of hdmf that gets installed through `pip install -e .` It should be something like `hdmf-3.7.1.dev2+g19c56f6`

When you do `pip install -e .`, a new file `src/hdmf/_version.py` should be created with the version string. Does that file get created?

**Comment by bendichter** [comment]
@rly the error might be due to the fact that I just updated hdmf without calling `pip install -e .` again. I did not have any problems running the above code.
