### ISSUE TITLE
[Bug]: Dev branches import failure from daily CI

### ISSUE THREAD

**Issue by CodyCBakerPhD** [hdmf-dev/hdmf#940]
### What happened?

Latest NeuroConv daily CI caught an HDMF import issue, wanted to make sure you're all aware of it

### Steps to Reproduce

```shell
https://github.com/catalystneuro/neuroconv/actions/runs/5858028094/job/15881154685
```

### Traceback

```pytb
ImportError while loading conftest '/home/runner/work/neuroconv/neuroconv/docs/conversion_examples_gallery/conftest.py'.
docs/conversion_examples_gallery/conftest.py:4: in <module>
    from tests.test_on_data.setup_paths import ECEPHY_DATA_PATH, BEHAVIOR_DATA_PATH, OPHYS_DATA_PATH, TEXT_DATA_PATH
tests/test_on_data/setup_paths.py:7: in <module>
    from neuroconv.utils import load_dict_from_file
src/neuroconv/__init__.py:1: in <module>
    from .basedatainterface import BaseDataInterface
src/neuroconv/basedatainterface.py:7: in <module>
    from pynwb import NWBFile
/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/pynwb/__init__.py:353: in <module>
    from . import io as __io  # noqa: F401,E402
/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/pynwb/io/__init__.py:1: in <module>
    from . import base as __base
/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/pynwb/io/base.py:3: in <module>
    from .core import NWBContainerMapper
/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/pynwb/io/core.py:9: in <module>
    from pynwb.file import NWBFile
/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/pynwb/file.py:11: in <module>
    from hdmf.container import ExternalResourcesManager
E   ImportError: cannot import name 'ExternalResourcesManager' from 'hdmf.container' (/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/hdmf/container.py)
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.8

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by oruebel** [comment]
Thanks @CodyCBakerPhD for the issue.   ExternalResourcesManager has been renamed in https://github.com/hdmf-dev/hdmf/pull/933 @mavaylon1 is working on a corresponding PR for PyNWB .

**Comment by mavaylon1** [comment]
@CodyCBakerPhD The fix should be out this week. We are merging some PRs into HDMF this week before doing a release. After the release, I will create a PR on pynwb to update the name change.

**Comment by rly** [comment]
Can you update the dev branch of pynwb first?
