### ISSUE TITLE
[Feature]: preview of docs changes in PRs

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#945]
### What would you like to see added to HDMF?

I would like PRs to automatically build the docs and show changes, similar to how this is set up in pynwb

<img width="854" alt="image" src="https://github.com/hdmf-dev/hdmf/assets/844306/56d4908b-3c75-49c0-a187-7e7e7f67c3cd">

### What solution would you like?

We could probably copy the workflow from pynwb

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by rly** [comment]
We already have that set up here.

<img width="868" alt="image" src="https://github.com/hdmf-dev/hdmf/assets/310197/74a49f73-69ab-4a43-a54e-7ef26194c7f4">

However, I think that making too many commits in a short window hits some sort of rate limit on the readthedocs PR builds and then it doesn't show up anymore...
