### ISSUE TITLE
[Feature]: TermSetWrapper with DataIO

### ISSUE THREAD

**Issue by mavaylon1** [hdmf-dev/hdmf#954]
### What would you like to see added to HDMF?

The `TermSetWrapper` class is meant to be used with HDF5 datasets and attributes. These datasets can also be used with `DataIO`. If a user wants to use both, we need to provide support for that functionality. The workflow would look something like 

-->H5DataIO(data=TermSetWrapper(item=data), compression=True)

This way the data is validated before going into DataIO. Once in DataIO, the wrapper would need (most likely) to be removed to not interfere with IO operations. 

### What solution would you like?

Refer Above.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by oruebel** [comment]
An alternative would be to swap the two, that is have `TermSetWrapper` wrap `H5DataIO`

``TermSetWrapper(item=H5DataIO(data=data), compression=True))``

In principal, I think either way is fine. With `TermSetWrapper` on the outside it may just work because `DataIO` exposes the data. With the option where `TermSetWrapper` is on the inside, we would probably need to unwrap the data for I/O. One option may be to update the `DataIO.data` property to do the unwrapping : 

https://github.com/hdmf-dev/hdmf/blob/ddc842b5c81d96e0b957b96e88533b16c137e206/src/hdmf/data_utils.py#L995-L998

**Comment by mavaylon1** [comment]
> An alternative would be to swap the two, that is have `TermSetWrapper` wrap `H5DataIO`
> 
> 
> 
> ``TermSetWrapper(item=H5DataIO(data=data), compression=True))``
> 
> 
> 
> In principal, I think either way is fine. With `TermSetWrapper` on the outside it may just work because `DataIO` exposes the data. With the option where `TermSetWrapper` is on the inside, we would probably need to unwrap the data for I/O. One option may be to update the `DataIO.data` property to do the unwrapping : 
> 
> 
> 
> https://github.com/hdmf-dev/hdmf/blob/ddc842b5c81d96e0b957b96e88533b16c137e206/src/hdmf/data_utils.py#L995-L998
> 
> 

I agree either way in practice is fine, but I think implicitly it makes sense that the TermSetWrapper comes first and wraps around the data to show its validating the data and not the IO Wrapper. Though that's just a mental preference I have.

**Comment by mavaylon1** [comment]
Similar to supporting iterative write with the wrapper, this is a special case that we will push back on till requested by the community.

**Comment by oruebel** [comment]
Did you test with

TermSetWrapper(item=H5DataIO(data=data), compression=True))

I think this should likely work as  is and may just need a couple of unit tests.
