### ISSUE TITLE
[Bug]: Auto-generating MultiContainerInterface subclasses

### ISSUE THREAD

**Issue by mavaylon1** [hdmf-dev/hdmf#959]
### What happened?

First alerted in #948, there is a bug from auto-generating class that inherits from `MultiContainerInterface`. In this example, `PlaneExtension` extends `PlaneSegmentation`, which inherits from `MultiContainerInterface` (you can see this in the schema with `reference_images` having quantity `*`. With extensions, NWBInspector does not see the python class definitions and will autogenerate the class from the schema. In this example, `PlaneExtension` is auto-generated. `PlaneExtension` inherits from both `MultiContainerInterface` and from `PlaneSegmentation`, which is a `DynamicTable`. 

Within `DynamicTable` is a pre-init method `_gather_columns` that uses the base classes in a conditional to create pre-defined columns. When autogenerating a class, the order of these classes are determined in lines 377-385 of classgenerator.py
```
if issubclass(MultiContainerInterface, bases[0]):
    # if bases[0] is Container or another superclass of MCI, then make sure MCI goes first
    # otherwise, MRO is ambiguous
    bases.insert(0, MultiContainerInterface)
else:
    # bases[0] is not a subclass of MCI and not a superclass of MCI. place that class first
    # before MCI. that class __init__ should call super().__init__ which will call the
    # MCI init
    bases.insert(1, MultiContainerInterface)
```
Since `MultiContainerInterface` is not a sub-class of `DynamicTable` (bases[0]), we insert at index 1. 

Within `gather_columns`, we check
```
if (len(bases) and 'DynamicTable' in globals() and issubclass(bases[-1], Container)
                and bases[-1].__columns__ is not cls.__columns__):
```
Such that bases[-1] (the last base in this case would be `MultiContainerInterface`) is assumed to be a `DynamicTable` and checks for columns. This returns the error: 
`AttributeError: type object 'MultiContainerInterface' has no attribute '__columns__'`

To fix this, the search for DynamicTable should be agnostic to the order of the bases. 

### Steps to Reproduce

```shell
# Run the extension or un-register a class.
```

### Operating System

macOS

### Python Executable

Python

### Python Version

3.10

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by mavaylon1** [comment]
I'll target this before the end of October.

**Comment by rly** [comment]
@mavaylon1 Could you tackle this issue this week?
