### ISSUE TITLE
Link on PyPI readme is broken

### ISSUE THREAD

**Issue by hed-maintainers** [hdmf-dev/hdmf#974]
### What would you like changed or added to the documentation and why?

On this page:  [https://pypi.org/project/hdmf/#description](https://pypi.org/project/hdmf/#description), the link to HDMF documentation under Installation is broken.

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by rly** [comment]
Thanks @hed-maintainers . We fixed this in #975. It will be updated on pypi.org in the next release.
